#include "../pb_export.h"
// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: perception/imgs.proto
#ifndef GRPC_perception_2fimgs_2eproto__INCLUDED
#define GRPC_perception_2fimgs_2eproto__INCLUDED

#include "perception/imgs.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace imageprocessing {

class PERCEPTION_API ImageProcessing final {
 public:
  static constexpr char const* service_full_name() {
    return "imageprocessing.ImageProcessing";
  }
  class PERCEPTION_API StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status singleTrack(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::imageprocessing::Tracks* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::imageprocessing::Tracks>> AsyncsingleTrack(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::imageprocessing::Tracks>>(AsyncsingleTrackRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::imageprocessing::Tracks>> PrepareAsyncsingleTrack(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::imageprocessing::Tracks>>(PrepareAsyncsingleTrackRaw(context, request, cq));
    }
    // a single call to the server with a single image, return tracking information 
    virtual ::grpc::Status singleMask(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::imageprocessing::MasksTracks* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::imageprocessing::MasksTracks>> AsyncsingleMask(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::imageprocessing::MasksTracks>>(AsyncsingleMaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::imageprocessing::MasksTracks>> PrepareAsyncsingleMask(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::imageprocessing::MasksTracks>>(PrepareAsyncsingleMaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::Tracks>> continuousTrack(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::Tracks>>(continuousTrackRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::Tracks>> AsynccontinuousTrack(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::Tracks>>(AsynccontinuousTrackRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::Tracks>> PrepareAsynccontinuousTrack(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::Tracks>>(PrepareAsynccontinuousTrackRaw(context, cq));
    }
    // a continuous stream of images, return tracking information
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::MasksTracks>> continuousMask(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::MasksTracks>>(continuousMaskRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::MasksTracks>> AsynccontinuousMask(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::MasksTracks>>(AsynccontinuousMaskRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::MasksTracks>> PrepareAsynccontinuousMask(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::MasksTracks>>(PrepareAsynccontinuousMaskRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::MasksTracks>> continuousInfo(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::MasksTracks>>(continuousInfoRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::MasksTracks>> AsynccontinuousInfo(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::MasksTracks>>(AsynccontinuousInfoRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::MasksTracks>> PrepareAsynccontinuousInfo(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::MasksTracks>>(PrepareAsynccontinuousInfoRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void singleTrack(::grpc::ClientContext* context, const ::imageprocessing::Img* request, ::imageprocessing::Tracks* response, std::function<void(::grpc::Status)>) = 0;
      virtual void singleTrack(::grpc::ClientContext* context, const ::imageprocessing::Img* request, ::imageprocessing::Tracks* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // a single call to the server with a single image, return tracking information 
      virtual void singleMask(::grpc::ClientContext* context, const ::imageprocessing::Img* request, ::imageprocessing::MasksTracks* response, std::function<void(::grpc::Status)>) = 0;
      virtual void singleMask(::grpc::ClientContext* context, const ::imageprocessing::Img* request, ::imageprocessing::MasksTracks* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void continuousTrack(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::imageprocessing::Img,::imageprocessing::Tracks>* reactor) = 0;
      // a continuous stream of images, return tracking information
      virtual void continuousMask(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::imageprocessing::Img,::imageprocessing::MasksTracks>* reactor) = 0;
      virtual void continuousInfo(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::imageprocessing::Img,::imageprocessing::MasksTracks>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::imageprocessing::Tracks>* AsyncsingleTrackRaw(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::imageprocessing::Tracks>* PrepareAsyncsingleTrackRaw(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::imageprocessing::MasksTracks>* AsyncsingleMaskRaw(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::imageprocessing::MasksTracks>* PrepareAsyncsingleMaskRaw(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::Tracks>* continuousTrackRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::Tracks>* AsynccontinuousTrackRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::Tracks>* PrepareAsynccontinuousTrackRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* continuousMaskRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* AsynccontinuousMaskRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* PrepareAsynccontinuousMaskRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* continuousInfoRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* AsynccontinuousInfoRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* PrepareAsynccontinuousInfoRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class PERCEPTION_API Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status singleTrack(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::imageprocessing::Tracks* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::imageprocessing::Tracks>> AsyncsingleTrack(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::imageprocessing::Tracks>>(AsyncsingleTrackRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::imageprocessing::Tracks>> PrepareAsyncsingleTrack(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::imageprocessing::Tracks>>(PrepareAsyncsingleTrackRaw(context, request, cq));
    }
    ::grpc::Status singleMask(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::imageprocessing::MasksTracks* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::imageprocessing::MasksTracks>> AsyncsingleMask(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::imageprocessing::MasksTracks>>(AsyncsingleMaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::imageprocessing::MasksTracks>> PrepareAsyncsingleMask(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::imageprocessing::MasksTracks>>(PrepareAsyncsingleMaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::imageprocessing::Img, ::imageprocessing::Tracks>> continuousTrack(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::imageprocessing::Img, ::imageprocessing::Tracks>>(continuousTrackRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::Tracks>> AsynccontinuousTrack(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::Tracks>>(AsynccontinuousTrackRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::Tracks>> PrepareAsynccontinuousTrack(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::Tracks>>(PrepareAsynccontinuousTrackRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>> continuousMask(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>>(continuousMaskRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>> AsynccontinuousMask(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>>(AsynccontinuousMaskRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>> PrepareAsynccontinuousMask(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>>(PrepareAsynccontinuousMaskRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>> continuousInfo(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>>(continuousInfoRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>> AsynccontinuousInfo(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>>(AsynccontinuousInfoRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>> PrepareAsynccontinuousInfo(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>>(PrepareAsynccontinuousInfoRaw(context, cq));
    }
    class PERCEPTION_API async final :
      public StubInterface::async_interface {
     public:
      void singleTrack(::grpc::ClientContext* context, const ::imageprocessing::Img* request, ::imageprocessing::Tracks* response, std::function<void(::grpc::Status)>) override;
      void singleTrack(::grpc::ClientContext* context, const ::imageprocessing::Img* request, ::imageprocessing::Tracks* response, ::grpc::ClientUnaryReactor* reactor) override;
      void singleMask(::grpc::ClientContext* context, const ::imageprocessing::Img* request, ::imageprocessing::MasksTracks* response, std::function<void(::grpc::Status)>) override;
      void singleMask(::grpc::ClientContext* context, const ::imageprocessing::Img* request, ::imageprocessing::MasksTracks* response, ::grpc::ClientUnaryReactor* reactor) override;
      void continuousTrack(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::imageprocessing::Img,::imageprocessing::Tracks>* reactor) override;
      void continuousMask(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::imageprocessing::Img,::imageprocessing::MasksTracks>* reactor) override;
      void continuousInfo(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::imageprocessing::Img,::imageprocessing::MasksTracks>* reactor) override;
     private:
      friend class PERCEPTION_API Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::imageprocessing::Tracks>* AsyncsingleTrackRaw(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::imageprocessing::Tracks>* PrepareAsyncsingleTrackRaw(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::imageprocessing::MasksTracks>* AsyncsingleMaskRaw(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::imageprocessing::MasksTracks>* PrepareAsyncsingleMaskRaw(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::imageprocessing::Img, ::imageprocessing::Tracks>* continuousTrackRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::Tracks>* AsynccontinuousTrackRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::Tracks>* PrepareAsynccontinuousTrackRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* continuousMaskRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* AsynccontinuousMaskRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* PrepareAsynccontinuousMaskRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* continuousInfoRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* AsynccontinuousInfoRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* PrepareAsynccontinuousInfoRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_singleTrack_;
    const ::grpc::internal::RpcMethod rpcmethod_singleMask_;
    const ::grpc::internal::RpcMethod rpcmethod_continuousTrack_;
    const ::grpc::internal::RpcMethod rpcmethod_continuousMask_;
    const ::grpc::internal::RpcMethod rpcmethod_continuousInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class PERCEPTION_API Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status singleTrack(::grpc::ServerContext* context, const ::imageprocessing::Img* request, ::imageprocessing::Tracks* response);
    // a single call to the server with a single image, return tracking information 
    virtual ::grpc::Status singleMask(::grpc::ServerContext* context, const ::imageprocessing::Img* request, ::imageprocessing::MasksTracks* response);
    virtual ::grpc::Status continuousTrack(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::imageprocessing::Tracks, ::imageprocessing::Img>* stream);
    // a continuous stream of images, return tracking information
    virtual ::grpc::Status continuousMask(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::imageprocessing::MasksTracks, ::imageprocessing::Img>* stream);
    virtual ::grpc::Status continuousInfo(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::imageprocessing::MasksTracks, ::imageprocessing::Img>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_singleTrack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_singleTrack() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_singleTrack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status singleTrack(::grpc::ServerContext* /*context*/, const ::imageprocessing::Img* /*request*/, ::imageprocessing::Tracks* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsingleTrack(::grpc::ServerContext* context, ::imageprocessing::Img* request, ::grpc::ServerAsyncResponseWriter< ::imageprocessing::Tracks>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_singleMask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_singleMask() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_singleMask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status singleMask(::grpc::ServerContext* /*context*/, const ::imageprocessing::Img* /*request*/, ::imageprocessing::MasksTracks* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsingleMask(::grpc::ServerContext* context, ::imageprocessing::Img* request, ::grpc::ServerAsyncResponseWriter< ::imageprocessing::MasksTracks>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_continuousTrack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_continuousTrack() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_continuousTrack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status continuousTrack(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageprocessing::Tracks, ::imageprocessing::Img>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcontinuousTrack(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::imageprocessing::Tracks, ::imageprocessing::Img>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_continuousMask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_continuousMask() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_continuousMask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status continuousMask(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageprocessing::MasksTracks, ::imageprocessing::Img>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcontinuousMask(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::imageprocessing::MasksTracks, ::imageprocessing::Img>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(3, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_continuousInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_continuousInfo() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_continuousInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status continuousInfo(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageprocessing::MasksTracks, ::imageprocessing::Img>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcontinuousInfo(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::imageprocessing::MasksTracks, ::imageprocessing::Img>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(4, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_singleTrack<WithAsyncMethod_singleMask<WithAsyncMethod_continuousTrack<WithAsyncMethod_continuousMask<WithAsyncMethod_continuousInfo<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_singleTrack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_singleTrack() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::imageprocessing::Img, ::imageprocessing::Tracks>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::imageprocessing::Img* request, ::imageprocessing::Tracks* response) { return this->singleTrack(context, request, response); }));}
    void SetMessageAllocatorFor_singleTrack(
        ::grpc::MessageAllocator< ::imageprocessing::Img, ::imageprocessing::Tracks>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::imageprocessing::Img, ::imageprocessing::Tracks>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_singleTrack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status singleTrack(::grpc::ServerContext* /*context*/, const ::imageprocessing::Img* /*request*/, ::imageprocessing::Tracks* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* singleTrack(
      ::grpc::CallbackServerContext* /*context*/, const ::imageprocessing::Img* /*request*/, ::imageprocessing::Tracks* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_singleMask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_singleMask() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::imageprocessing::Img, ::imageprocessing::MasksTracks>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::imageprocessing::Img* request, ::imageprocessing::MasksTracks* response) { return this->singleMask(context, request, response); }));}
    void SetMessageAllocatorFor_singleMask(
        ::grpc::MessageAllocator< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::imageprocessing::Img, ::imageprocessing::MasksTracks>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_singleMask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status singleMask(::grpc::ServerContext* /*context*/, const ::imageprocessing::Img* /*request*/, ::imageprocessing::MasksTracks* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* singleMask(
      ::grpc::CallbackServerContext* /*context*/, const ::imageprocessing::Img* /*request*/, ::imageprocessing::MasksTracks* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_continuousTrack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_continuousTrack() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackBidiHandler< ::imageprocessing::Img, ::imageprocessing::Tracks>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->continuousTrack(context); }));
    }
    ~WithCallbackMethod_continuousTrack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status continuousTrack(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageprocessing::Tracks, ::imageprocessing::Img>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::imageprocessing::Img, ::imageprocessing::Tracks>* continuousTrack(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_continuousMask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_continuousMask() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackBidiHandler< ::imageprocessing::Img, ::imageprocessing::MasksTracks>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->continuousMask(context); }));
    }
    ~WithCallbackMethod_continuousMask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status continuousMask(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageprocessing::MasksTracks, ::imageprocessing::Img>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* continuousMask(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_continuousInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_continuousInfo() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackBidiHandler< ::imageprocessing::Img, ::imageprocessing::MasksTracks>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->continuousInfo(context); }));
    }
    ~WithCallbackMethod_continuousInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status continuousInfo(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageprocessing::MasksTracks, ::imageprocessing::Img>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* continuousInfo(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_singleTrack<WithCallbackMethod_singleMask<WithCallbackMethod_continuousTrack<WithCallbackMethod_continuousMask<WithCallbackMethod_continuousInfo<Service > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_singleTrack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_singleTrack() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_singleTrack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status singleTrack(::grpc::ServerContext* /*context*/, const ::imageprocessing::Img* /*request*/, ::imageprocessing::Tracks* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_singleMask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_singleMask() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_singleMask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status singleMask(::grpc::ServerContext* /*context*/, const ::imageprocessing::Img* /*request*/, ::imageprocessing::MasksTracks* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_continuousTrack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_continuousTrack() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_continuousTrack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status continuousTrack(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageprocessing::Tracks, ::imageprocessing::Img>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_continuousMask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_continuousMask() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_continuousMask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status continuousMask(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageprocessing::MasksTracks, ::imageprocessing::Img>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_continuousInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_continuousInfo() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_continuousInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status continuousInfo(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageprocessing::MasksTracks, ::imageprocessing::Img>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_singleTrack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_singleTrack() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_singleTrack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status singleTrack(::grpc::ServerContext* /*context*/, const ::imageprocessing::Img* /*request*/, ::imageprocessing::Tracks* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsingleTrack(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_singleMask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_singleMask() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_singleMask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status singleMask(::grpc::ServerContext* /*context*/, const ::imageprocessing::Img* /*request*/, ::imageprocessing::MasksTracks* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsingleMask(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_continuousTrack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_continuousTrack() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_continuousTrack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status continuousTrack(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageprocessing::Tracks, ::imageprocessing::Img>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcontinuousTrack(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_continuousMask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_continuousMask() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_continuousMask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status continuousMask(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageprocessing::MasksTracks, ::imageprocessing::Img>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcontinuousMask(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(3, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_continuousInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_continuousInfo() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_continuousInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status continuousInfo(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageprocessing::MasksTracks, ::imageprocessing::Img>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcontinuousInfo(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(4, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_singleTrack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_singleTrack() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->singleTrack(context, request, response); }));
    }
    ~WithRawCallbackMethod_singleTrack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status singleTrack(::grpc::ServerContext* /*context*/, const ::imageprocessing::Img* /*request*/, ::imageprocessing::Tracks* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* singleTrack(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_singleMask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_singleMask() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->singleMask(context, request, response); }));
    }
    ~WithRawCallbackMethod_singleMask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status singleMask(::grpc::ServerContext* /*context*/, const ::imageprocessing::Img* /*request*/, ::imageprocessing::MasksTracks* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* singleMask(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_continuousTrack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_continuousTrack() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->continuousTrack(context); }));
    }
    ~WithRawCallbackMethod_continuousTrack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status continuousTrack(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageprocessing::Tracks, ::imageprocessing::Img>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* continuousTrack(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_continuousMask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_continuousMask() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->continuousMask(context); }));
    }
    ~WithRawCallbackMethod_continuousMask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status continuousMask(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageprocessing::MasksTracks, ::imageprocessing::Img>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* continuousMask(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_continuousInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_continuousInfo() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->continuousInfo(context); }));
    }
    ~WithRawCallbackMethod_continuousInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status continuousInfo(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageprocessing::MasksTracks, ::imageprocessing::Img>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* continuousInfo(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_singleTrack : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_singleTrack() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::imageprocessing::Img, ::imageprocessing::Tracks>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::imageprocessing::Img, ::imageprocessing::Tracks>* streamer) {
                       return this->StreamedsingleTrack(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_singleTrack() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status singleTrack(::grpc::ServerContext* /*context*/, const ::imageprocessing::Img* /*request*/, ::imageprocessing::Tracks* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsingleTrack(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::imageprocessing::Img,::imageprocessing::Tracks>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_singleMask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_singleMask() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::imageprocessing::Img, ::imageprocessing::MasksTracks>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::imageprocessing::Img, ::imageprocessing::MasksTracks>* streamer) {
                       return this->StreamedsingleMask(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_singleMask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status singleMask(::grpc::ServerContext* /*context*/, const ::imageprocessing::Img* /*request*/, ::imageprocessing::MasksTracks* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsingleMask(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::imageprocessing::Img,::imageprocessing::MasksTracks>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_singleTrack<WithStreamedUnaryMethod_singleMask<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_singleTrack<WithStreamedUnaryMethod_singleMask<Service > > StreamedService;
};
// define the process of taking in image(s) from navigation system 
// and sending out masks to downstream system

}  // namespace imageprocessing


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_perception_2fimgs_2eproto__INCLUDED
