#include "../pb_export.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: perception/imgs.proto
// Protobuf C++ Version: 5.29.3

#ifndef perception_2fimgs_2eproto_2epb_2eh
#define perception_2fimgs_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_perception_2fimgs_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_perception_2fimgs_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_perception_2fimgs_2eproto;
namespace imageprocessing {
class Img;
struct ImgDefaultTypeInternal;
extern ImgDefaultTypeInternal _Img_default_instance_;
class Masks;
struct MasksDefaultTypeInternal;
extern MasksDefaultTypeInternal _Masks_default_instance_;
class MasksTracks;
struct MasksTracksDefaultTypeInternal;
extern MasksTracksDefaultTypeInternal _MasksTracks_default_instance_;
class TrackRow;
struct TrackRowDefaultTypeInternal;
extern TrackRowDefaultTypeInternal _TrackRow_default_instance_;
class Tracks;
struct TracksDefaultTypeInternal;
extern TracksDefaultTypeInternal _Tracks_default_instance_;
}  // namespace imageprocessing
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace imageprocessing {

// ===================================================================


// -------------------------------------------------------------------

class PERCEPTION_API Tracks final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:imageprocessing.Tracks) */ {
 public:
  inline Tracks() : Tracks(nullptr) {}
  ~Tracks() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Tracks* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Tracks));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Tracks(
      ::google::protobuf::internal::ConstantInitialized);

  inline Tracks(const Tracks& from) : Tracks(nullptr, from) {}
  inline Tracks(Tracks&& from) noexcept
      : Tracks(nullptr, std::move(from)) {}
  inline Tracks& operator=(const Tracks& from) {
    CopyFrom(from);
    return *this;
  }
  inline Tracks& operator=(Tracks&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Tracks& default_instance() {
    return *internal_default_instance();
  }
  static inline const Tracks* internal_default_instance() {
    return reinterpret_cast<const Tracks*>(
        &_Tracks_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Tracks& a, Tracks& b) { a.Swap(&b); }
  inline void Swap(Tracks* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Tracks* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Tracks* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Tracks>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Tracks& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Tracks& from) { Tracks::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Tracks* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "imageprocessing.Tracks"; }

 protected:
  explicit Tracks(::google::protobuf::Arena* arena);
  Tracks(::google::protobuf::Arena* arena, const Tracks& from);
  Tracks(::google::protobuf::Arena* arena, Tracks&& from) noexcept
      : Tracks(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTimeStampFieldNumber = 1,
    kTracksFieldNumber = 2,
  };
  // bytes timeStamp = 1;
  void clear_timestamp() ;
  const std::string& timestamp() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_timestamp(Arg_&& arg, Args_... args);
  std::string* mutable_timestamp();
  PROTOBUF_NODISCARD std::string* release_timestamp();
  void set_allocated_timestamp(std::string* value);

  private:
  const std::string& _internal_timestamp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_timestamp(
      const std::string& value);
  std::string* _internal_mutable_timestamp();

  public:
  // bytes tracks = 2;
  void clear_tracks() ;
  const std::string& tracks() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_tracks(Arg_&& arg, Args_... args);
  std::string* mutable_tracks();
  PROTOBUF_NODISCARD std::string* release_tracks();
  void set_allocated_tracks(std::string* value);

  private:
  const std::string& _internal_tracks() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_tracks(
      const std::string& value);
  std::string* _internal_mutable_tracks();

  public:
  // @@protoc_insertion_point(class_scope:imageprocessing.Tracks)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Tracks& from_msg);
    ::google::protobuf::internal::ArenaStringPtr timestamp_;
    ::google::protobuf::internal::ArenaStringPtr tracks_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_perception_2fimgs_2eproto;
};
// -------------------------------------------------------------------

class PERCEPTION_API Masks final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:imageprocessing.Masks) */ {
 public:
  inline Masks() : Masks(nullptr) {}
  ~Masks() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Masks* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Masks));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Masks(
      ::google::protobuf::internal::ConstantInitialized);

  inline Masks(const Masks& from) : Masks(nullptr, from) {}
  inline Masks(Masks&& from) noexcept
      : Masks(nullptr, std::move(from)) {}
  inline Masks& operator=(const Masks& from) {
    CopyFrom(from);
    return *this;
  }
  inline Masks& operator=(Masks&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Masks& default_instance() {
    return *internal_default_instance();
  }
  static inline const Masks* internal_default_instance() {
    return reinterpret_cast<const Masks*>(
        &_Masks_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(Masks& a, Masks& b) { a.Swap(&b); }
  inline void Swap(Masks* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Masks* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Masks* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Masks>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Masks& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Masks& from) { Masks::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Masks* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "imageprocessing.Masks"; }

 protected:
  explicit Masks(::google::protobuf::Arena* arena);
  Masks(::google::protobuf::Arena* arena, const Masks& from);
  Masks(::google::protobuf::Arena* arena, Masks&& from) noexcept
      : Masks(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // int32 x = 1;
  void clear_x() ;
  ::int32_t x() const;
  void set_x(::int32_t value);

  private:
  ::int32_t _internal_x() const;
  void _internal_set_x(::int32_t value);

  public:
  // int32 y = 2;
  void clear_y() ;
  ::int32_t y() const;
  void set_y(::int32_t value);

  private:
  ::int32_t _internal_y() const;
  void _internal_set_y(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:imageprocessing.Masks)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Masks& from_msg);
    ::int32_t x_;
    ::int32_t y_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_perception_2fimgs_2eproto;
};
// -------------------------------------------------------------------

class PERCEPTION_API Img final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:imageprocessing.Img) */ {
 public:
  inline Img() : Img(nullptr) {}
  ~Img() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Img* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Img));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Img(
      ::google::protobuf::internal::ConstantInitialized);

  inline Img(const Img& from) : Img(nullptr, from) {}
  inline Img(Img&& from) noexcept
      : Img(nullptr, std::move(from)) {}
  inline Img& operator=(const Img& from) {
    CopyFrom(from);
    return *this;
  }
  inline Img& operator=(Img&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Img& default_instance() {
    return *internal_default_instance();
  }
  static inline const Img* internal_default_instance() {
    return reinterpret_cast<const Img*>(
        &_Img_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Img& a, Img& b) { a.Swap(&b); }
  inline void Swap(Img* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Img* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Img* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Img>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Img& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Img& from) { Img::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Img* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "imageprocessing.Img"; }

 protected:
  explicit Img(::google::protobuf::Arena* arena);
  Img(::google::protobuf::Arena* arena, const Img& from);
  Img(::google::protobuf::Arena* arena, Img&& from) noexcept
      : Img(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTimeStampFieldNumber = 1,
    kImgFieldNumber = 2,
    kRequiresMasksFieldNumber = 3,
  };
  // bytes timeStamp = 1;
  void clear_timestamp() ;
  const std::string& timestamp() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_timestamp(Arg_&& arg, Args_... args);
  std::string* mutable_timestamp();
  PROTOBUF_NODISCARD std::string* release_timestamp();
  void set_allocated_timestamp(std::string* value);

  private:
  const std::string& _internal_timestamp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_timestamp(
      const std::string& value);
  std::string* _internal_mutable_timestamp();

  public:
  // bytes img = 2;
  void clear_img() ;
  const std::string& img() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_img(Arg_&& arg, Args_... args);
  std::string* mutable_img();
  PROTOBUF_NODISCARD std::string* release_img();
  void set_allocated_img(std::string* value);

  private:
  const std::string& _internal_img() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_img(
      const std::string& value);
  std::string* _internal_mutable_img();

  public:
  // bool requiresMasks = 3;
  void clear_requiresmasks() ;
  bool requiresmasks() const;
  void set_requiresmasks(bool value);

  private:
  bool _internal_requiresmasks() const;
  void _internal_set_requiresmasks(bool value);

  public:
  // @@protoc_insertion_point(class_scope:imageprocessing.Img)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Img& from_msg);
    ::google::protobuf::internal::ArenaStringPtr timestamp_;
    ::google::protobuf::internal::ArenaStringPtr img_;
    bool requiresmasks_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_perception_2fimgs_2eproto;
};
// -------------------------------------------------------------------

class PERCEPTION_API TrackRow final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:imageprocessing.TrackRow) */ {
 public:
  inline TrackRow() : TrackRow(nullptr) {}
  ~TrackRow() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TrackRow* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TrackRow));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TrackRow(
      ::google::protobuf::internal::ConstantInitialized);

  inline TrackRow(const TrackRow& from) : TrackRow(nullptr, from) {}
  inline TrackRow(TrackRow&& from) noexcept
      : TrackRow(nullptr, std::move(from)) {}
  inline TrackRow& operator=(const TrackRow& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrackRow& operator=(TrackRow&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TrackRow& default_instance() {
    return *internal_default_instance();
  }
  static inline const TrackRow* internal_default_instance() {
    return reinterpret_cast<const TrackRow*>(
        &_TrackRow_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(TrackRow& a, TrackRow& b) { a.Swap(&b); }
  inline void Swap(TrackRow* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrackRow* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TrackRow* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TrackRow>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TrackRow& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TrackRow& from) { TrackRow::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TrackRow* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "imageprocessing.TrackRow"; }

 protected:
  explicit TrackRow(::google::protobuf::Arena* arena);
  TrackRow(::google::protobuf::Arena* arena, const TrackRow& from);
  TrackRow(::google::protobuf::Arena* arena, TrackRow&& from) noexcept
      : TrackRow(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMaskFieldNumber = 8,
    kTrackIdFieldNumber = 5,
    kClsFieldNumber = 7,
    kX1FieldNumber = 1,
    kY1FieldNumber = 2,
    kX2FieldNumber = 3,
    kY2FieldNumber = 4,
    kConfFieldNumber = 6,
  };
  // repeated .imageprocessing.Masks mask = 8;
  int mask_size() const;
  private:
  int _internal_mask_size() const;

  public:
  void clear_mask() ;
  ::imageprocessing::Masks* mutable_mask(int index);
  ::google::protobuf::RepeatedPtrField<::imageprocessing::Masks>* mutable_mask();

  private:
  const ::google::protobuf::RepeatedPtrField<::imageprocessing::Masks>& _internal_mask() const;
  ::google::protobuf::RepeatedPtrField<::imageprocessing::Masks>* _internal_mutable_mask();
  public:
  const ::imageprocessing::Masks& mask(int index) const;
  ::imageprocessing::Masks* add_mask();
  const ::google::protobuf::RepeatedPtrField<::imageprocessing::Masks>& mask() const;
  // string trackId = 5;
  void clear_trackid() ;
  const std::string& trackid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_trackid(Arg_&& arg, Args_... args);
  std::string* mutable_trackid();
  PROTOBUF_NODISCARD std::string* release_trackid();
  void set_allocated_trackid(std::string* value);

  private:
  const std::string& _internal_trackid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_trackid(
      const std::string& value);
  std::string* _internal_mutable_trackid();

  public:
  // string cls = 7;
  void clear_cls() ;
  const std::string& cls() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_cls(Arg_&& arg, Args_... args);
  std::string* mutable_cls();
  PROTOBUF_NODISCARD std::string* release_cls();
  void set_allocated_cls(std::string* value);

  private:
  const std::string& _internal_cls() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cls(
      const std::string& value);
  std::string* _internal_mutable_cls();

  public:
  // float x1 = 1;
  void clear_x1() ;
  float x1() const;
  void set_x1(float value);

  private:
  float _internal_x1() const;
  void _internal_set_x1(float value);

  public:
  // float y1 = 2;
  void clear_y1() ;
  float y1() const;
  void set_y1(float value);

  private:
  float _internal_y1() const;
  void _internal_set_y1(float value);

  public:
  // float x2 = 3;
  void clear_x2() ;
  float x2() const;
  void set_x2(float value);

  private:
  float _internal_x2() const;
  void _internal_set_x2(float value);

  public:
  // float y2 = 4;
  void clear_y2() ;
  float y2() const;
  void set_y2(float value);

  private:
  float _internal_y2() const;
  void _internal_set_y2(float value);

  public:
  // float conf = 6;
  void clear_conf() ;
  float conf() const;
  void set_conf(float value);

  private:
  float _internal_conf() const;
  void _internal_set_conf(float value);

  public:
  // @@protoc_insertion_point(class_scope:imageprocessing.TrackRow)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 8, 1,
      51, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const TrackRow& from_msg);
    ::google::protobuf::RepeatedPtrField< ::imageprocessing::Masks > mask_;
    ::google::protobuf::internal::ArenaStringPtr trackid_;
    ::google::protobuf::internal::ArenaStringPtr cls_;
    float x1_;
    float y1_;
    float x2_;
    float y2_;
    float conf_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_perception_2fimgs_2eproto;
};
// -------------------------------------------------------------------

class PERCEPTION_API MasksTracks final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:imageprocessing.MasksTracks) */ {
 public:
  inline MasksTracks() : MasksTracks(nullptr) {}
  ~MasksTracks() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MasksTracks* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MasksTracks));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MasksTracks(
      ::google::protobuf::internal::ConstantInitialized);

  inline MasksTracks(const MasksTracks& from) : MasksTracks(nullptr, from) {}
  inline MasksTracks(MasksTracks&& from) noexcept
      : MasksTracks(nullptr, std::move(from)) {}
  inline MasksTracks& operator=(const MasksTracks& from) {
    CopyFrom(from);
    return *this;
  }
  inline MasksTracks& operator=(MasksTracks&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MasksTracks& default_instance() {
    return *internal_default_instance();
  }
  static inline const MasksTracks* internal_default_instance() {
    return reinterpret_cast<const MasksTracks*>(
        &_MasksTracks_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(MasksTracks& a, MasksTracks& b) { a.Swap(&b); }
  inline void Swap(MasksTracks* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MasksTracks* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MasksTracks* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MasksTracks>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MasksTracks& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MasksTracks& from) { MasksTracks::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MasksTracks* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "imageprocessing.MasksTracks"; }

 protected:
  explicit MasksTracks(::google::protobuf::Arena* arena);
  MasksTracks(::google::protobuf::Arena* arena, const MasksTracks& from);
  MasksTracks(::google::protobuf::Arena* arena, MasksTracks&& from) noexcept
      : MasksTracks(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTracksFieldNumber = 2,
    kTimeStampFieldNumber = 1,
  };
  // repeated .imageprocessing.TrackRow tracks = 2;
  int tracks_size() const;
  private:
  int _internal_tracks_size() const;

  public:
  void clear_tracks() ;
  ::imageprocessing::TrackRow* mutable_tracks(int index);
  ::google::protobuf::RepeatedPtrField<::imageprocessing::TrackRow>* mutable_tracks();

  private:
  const ::google::protobuf::RepeatedPtrField<::imageprocessing::TrackRow>& _internal_tracks() const;
  ::google::protobuf::RepeatedPtrField<::imageprocessing::TrackRow>* _internal_mutable_tracks();
  public:
  const ::imageprocessing::TrackRow& tracks(int index) const;
  ::imageprocessing::TrackRow* add_tracks();
  const ::google::protobuf::RepeatedPtrField<::imageprocessing::TrackRow>& tracks() const;
  // bytes timeStamp = 1;
  void clear_timestamp() ;
  const std::string& timestamp() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_timestamp(Arg_&& arg, Args_... args);
  std::string* mutable_timestamp();
  PROTOBUF_NODISCARD std::string* release_timestamp();
  void set_allocated_timestamp(std::string* value);

  private:
  const std::string& _internal_timestamp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_timestamp(
      const std::string& value);
  std::string* _internal_mutable_timestamp();

  public:
  // @@protoc_insertion_point(class_scope:imageprocessing.MasksTracks)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MasksTracks& from_msg);
    ::google::protobuf::RepeatedPtrField< ::imageprocessing::TrackRow > tracks_;
    ::google::protobuf::internal::ArenaStringPtr timestamp_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_perception_2fimgs_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Img

// bytes timeStamp = 1;
inline void Img::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_.ClearToEmpty();
}
inline const std::string& Img::timestamp() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:imageprocessing.Img.timeStamp)
  return _internal_timestamp();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Img::set_timestamp(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:imageprocessing.Img.timeStamp)
}
inline std::string* Img::mutable_timestamp() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:imageprocessing.Img.timeStamp)
  return _s;
}
inline const std::string& Img::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_.Get();
}
inline void Img::_internal_set_timestamp(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_.Set(value, GetArena());
}
inline std::string* Img::_internal_mutable_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.timestamp_.Mutable( GetArena());
}
inline std::string* Img::release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:imageprocessing.Img.timeStamp)
  return _impl_.timestamp_.Release();
}
inline void Img::set_allocated_timestamp(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.timestamp_.IsDefault()) {
    _impl_.timestamp_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:imageprocessing.Img.timeStamp)
}

// bytes img = 2;
inline void Img::clear_img() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.img_.ClearToEmpty();
}
inline const std::string& Img::img() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:imageprocessing.Img.img)
  return _internal_img();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Img::set_img(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.img_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:imageprocessing.Img.img)
}
inline std::string* Img::mutable_img() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_img();
  // @@protoc_insertion_point(field_mutable:imageprocessing.Img.img)
  return _s;
}
inline const std::string& Img::_internal_img() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.img_.Get();
}
inline void Img::_internal_set_img(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.img_.Set(value, GetArena());
}
inline std::string* Img::_internal_mutable_img() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.img_.Mutable( GetArena());
}
inline std::string* Img::release_img() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:imageprocessing.Img.img)
  return _impl_.img_.Release();
}
inline void Img::set_allocated_img(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.img_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.img_.IsDefault()) {
    _impl_.img_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:imageprocessing.Img.img)
}

// bool requiresMasks = 3;
inline void Img::clear_requiresmasks() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.requiresmasks_ = false;
}
inline bool Img::requiresmasks() const {
  // @@protoc_insertion_point(field_get:imageprocessing.Img.requiresMasks)
  return _internal_requiresmasks();
}
inline void Img::set_requiresmasks(bool value) {
  _internal_set_requiresmasks(value);
  // @@protoc_insertion_point(field_set:imageprocessing.Img.requiresMasks)
}
inline bool Img::_internal_requiresmasks() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.requiresmasks_;
}
inline void Img::_internal_set_requiresmasks(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.requiresmasks_ = value;
}

// -------------------------------------------------------------------

// Tracks

// bytes timeStamp = 1;
inline void Tracks::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_.ClearToEmpty();
}
inline const std::string& Tracks::timestamp() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:imageprocessing.Tracks.timeStamp)
  return _internal_timestamp();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Tracks::set_timestamp(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:imageprocessing.Tracks.timeStamp)
}
inline std::string* Tracks::mutable_timestamp() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:imageprocessing.Tracks.timeStamp)
  return _s;
}
inline const std::string& Tracks::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_.Get();
}
inline void Tracks::_internal_set_timestamp(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_.Set(value, GetArena());
}
inline std::string* Tracks::_internal_mutable_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.timestamp_.Mutable( GetArena());
}
inline std::string* Tracks::release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:imageprocessing.Tracks.timeStamp)
  return _impl_.timestamp_.Release();
}
inline void Tracks::set_allocated_timestamp(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.timestamp_.IsDefault()) {
    _impl_.timestamp_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:imageprocessing.Tracks.timeStamp)
}

// bytes tracks = 2;
inline void Tracks::clear_tracks() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tracks_.ClearToEmpty();
}
inline const std::string& Tracks::tracks() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:imageprocessing.Tracks.tracks)
  return _internal_tracks();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Tracks::set_tracks(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tracks_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:imageprocessing.Tracks.tracks)
}
inline std::string* Tracks::mutable_tracks() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_tracks();
  // @@protoc_insertion_point(field_mutable:imageprocessing.Tracks.tracks)
  return _s;
}
inline const std::string& Tracks::_internal_tracks() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tracks_.Get();
}
inline void Tracks::_internal_set_tracks(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tracks_.Set(value, GetArena());
}
inline std::string* Tracks::_internal_mutable_tracks() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.tracks_.Mutable( GetArena());
}
inline std::string* Tracks::release_tracks() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:imageprocessing.Tracks.tracks)
  return _impl_.tracks_.Release();
}
inline void Tracks::set_allocated_tracks(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tracks_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.tracks_.IsDefault()) {
    _impl_.tracks_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:imageprocessing.Tracks.tracks)
}

// -------------------------------------------------------------------

// MasksTracks

// bytes timeStamp = 1;
inline void MasksTracks::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_.ClearToEmpty();
}
inline const std::string& MasksTracks::timestamp() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:imageprocessing.MasksTracks.timeStamp)
  return _internal_timestamp();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void MasksTracks::set_timestamp(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:imageprocessing.MasksTracks.timeStamp)
}
inline std::string* MasksTracks::mutable_timestamp() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:imageprocessing.MasksTracks.timeStamp)
  return _s;
}
inline const std::string& MasksTracks::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_.Get();
}
inline void MasksTracks::_internal_set_timestamp(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_.Set(value, GetArena());
}
inline std::string* MasksTracks::_internal_mutable_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.timestamp_.Mutable( GetArena());
}
inline std::string* MasksTracks::release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:imageprocessing.MasksTracks.timeStamp)
  return _impl_.timestamp_.Release();
}
inline void MasksTracks::set_allocated_timestamp(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.timestamp_.IsDefault()) {
    _impl_.timestamp_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:imageprocessing.MasksTracks.timeStamp)
}

// repeated .imageprocessing.TrackRow tracks = 2;
inline int MasksTracks::_internal_tracks_size() const {
  return _internal_tracks().size();
}
inline int MasksTracks::tracks_size() const {
  return _internal_tracks_size();
}
inline void MasksTracks::clear_tracks() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tracks_.Clear();
}
inline ::imageprocessing::TrackRow* MasksTracks::mutable_tracks(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:imageprocessing.MasksTracks.tracks)
  return _internal_mutable_tracks()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::imageprocessing::TrackRow>* MasksTracks::mutable_tracks()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:imageprocessing.MasksTracks.tracks)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_tracks();
}
inline const ::imageprocessing::TrackRow& MasksTracks::tracks(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:imageprocessing.MasksTracks.tracks)
  return _internal_tracks().Get(index);
}
inline ::imageprocessing::TrackRow* MasksTracks::add_tracks() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::imageprocessing::TrackRow* _add = _internal_mutable_tracks()->Add();
  // @@protoc_insertion_point(field_add:imageprocessing.MasksTracks.tracks)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::imageprocessing::TrackRow>& MasksTracks::tracks() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:imageprocessing.MasksTracks.tracks)
  return _internal_tracks();
}
inline const ::google::protobuf::RepeatedPtrField<::imageprocessing::TrackRow>&
MasksTracks::_internal_tracks() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tracks_;
}
inline ::google::protobuf::RepeatedPtrField<::imageprocessing::TrackRow>*
MasksTracks::_internal_mutable_tracks() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.tracks_;
}

// -------------------------------------------------------------------

// TrackRow

// float x1 = 1;
inline void TrackRow::clear_x1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x1_ = 0;
}
inline float TrackRow::x1() const {
  // @@protoc_insertion_point(field_get:imageprocessing.TrackRow.x1)
  return _internal_x1();
}
inline void TrackRow::set_x1(float value) {
  _internal_set_x1(value);
  // @@protoc_insertion_point(field_set:imageprocessing.TrackRow.x1)
}
inline float TrackRow::_internal_x1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x1_;
}
inline void TrackRow::_internal_set_x1(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x1_ = value;
}

// float y1 = 2;
inline void TrackRow::clear_y1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y1_ = 0;
}
inline float TrackRow::y1() const {
  // @@protoc_insertion_point(field_get:imageprocessing.TrackRow.y1)
  return _internal_y1();
}
inline void TrackRow::set_y1(float value) {
  _internal_set_y1(value);
  // @@protoc_insertion_point(field_set:imageprocessing.TrackRow.y1)
}
inline float TrackRow::_internal_y1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y1_;
}
inline void TrackRow::_internal_set_y1(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y1_ = value;
}

// float x2 = 3;
inline void TrackRow::clear_x2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x2_ = 0;
}
inline float TrackRow::x2() const {
  // @@protoc_insertion_point(field_get:imageprocessing.TrackRow.x2)
  return _internal_x2();
}
inline void TrackRow::set_x2(float value) {
  _internal_set_x2(value);
  // @@protoc_insertion_point(field_set:imageprocessing.TrackRow.x2)
}
inline float TrackRow::_internal_x2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x2_;
}
inline void TrackRow::_internal_set_x2(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x2_ = value;
}

// float y2 = 4;
inline void TrackRow::clear_y2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y2_ = 0;
}
inline float TrackRow::y2() const {
  // @@protoc_insertion_point(field_get:imageprocessing.TrackRow.y2)
  return _internal_y2();
}
inline void TrackRow::set_y2(float value) {
  _internal_set_y2(value);
  // @@protoc_insertion_point(field_set:imageprocessing.TrackRow.y2)
}
inline float TrackRow::_internal_y2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y2_;
}
inline void TrackRow::_internal_set_y2(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y2_ = value;
}

// string trackId = 5;
inline void TrackRow::clear_trackid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.trackid_.ClearToEmpty();
}
inline const std::string& TrackRow::trackid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:imageprocessing.TrackRow.trackId)
  return _internal_trackid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TrackRow::set_trackid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.trackid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:imageprocessing.TrackRow.trackId)
}
inline std::string* TrackRow::mutable_trackid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_trackid();
  // @@protoc_insertion_point(field_mutable:imageprocessing.TrackRow.trackId)
  return _s;
}
inline const std::string& TrackRow::_internal_trackid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.trackid_.Get();
}
inline void TrackRow::_internal_set_trackid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.trackid_.Set(value, GetArena());
}
inline std::string* TrackRow::_internal_mutable_trackid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.trackid_.Mutable( GetArena());
}
inline std::string* TrackRow::release_trackid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:imageprocessing.TrackRow.trackId)
  return _impl_.trackid_.Release();
}
inline void TrackRow::set_allocated_trackid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.trackid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.trackid_.IsDefault()) {
    _impl_.trackid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:imageprocessing.TrackRow.trackId)
}

// float conf = 6;
inline void TrackRow::clear_conf() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.conf_ = 0;
}
inline float TrackRow::conf() const {
  // @@protoc_insertion_point(field_get:imageprocessing.TrackRow.conf)
  return _internal_conf();
}
inline void TrackRow::set_conf(float value) {
  _internal_set_conf(value);
  // @@protoc_insertion_point(field_set:imageprocessing.TrackRow.conf)
}
inline float TrackRow::_internal_conf() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.conf_;
}
inline void TrackRow::_internal_set_conf(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.conf_ = value;
}

// string cls = 7;
inline void TrackRow::clear_cls() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cls_.ClearToEmpty();
}
inline const std::string& TrackRow::cls() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:imageprocessing.TrackRow.cls)
  return _internal_cls();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TrackRow::set_cls(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cls_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:imageprocessing.TrackRow.cls)
}
inline std::string* TrackRow::mutable_cls() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_cls();
  // @@protoc_insertion_point(field_mutable:imageprocessing.TrackRow.cls)
  return _s;
}
inline const std::string& TrackRow::_internal_cls() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cls_.Get();
}
inline void TrackRow::_internal_set_cls(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cls_.Set(value, GetArena());
}
inline std::string* TrackRow::_internal_mutable_cls() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cls_.Mutable( GetArena());
}
inline std::string* TrackRow::release_cls() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:imageprocessing.TrackRow.cls)
  return _impl_.cls_.Release();
}
inline void TrackRow::set_allocated_cls(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cls_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cls_.IsDefault()) {
    _impl_.cls_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:imageprocessing.TrackRow.cls)
}

// repeated .imageprocessing.Masks mask = 8;
inline int TrackRow::_internal_mask_size() const {
  return _internal_mask().size();
}
inline int TrackRow::mask_size() const {
  return _internal_mask_size();
}
inline void TrackRow::clear_mask() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mask_.Clear();
}
inline ::imageprocessing::Masks* TrackRow::mutable_mask(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:imageprocessing.TrackRow.mask)
  return _internal_mutable_mask()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::imageprocessing::Masks>* TrackRow::mutable_mask()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:imageprocessing.TrackRow.mask)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_mask();
}
inline const ::imageprocessing::Masks& TrackRow::mask(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:imageprocessing.TrackRow.mask)
  return _internal_mask().Get(index);
}
inline ::imageprocessing::Masks* TrackRow::add_mask() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::imageprocessing::Masks* _add = _internal_mutable_mask()->Add();
  // @@protoc_insertion_point(field_add:imageprocessing.TrackRow.mask)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::imageprocessing::Masks>& TrackRow::mask() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:imageprocessing.TrackRow.mask)
  return _internal_mask();
}
inline const ::google::protobuf::RepeatedPtrField<::imageprocessing::Masks>&
TrackRow::_internal_mask() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mask_;
}
inline ::google::protobuf::RepeatedPtrField<::imageprocessing::Masks>*
TrackRow::_internal_mutable_mask() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.mask_;
}

// -------------------------------------------------------------------

// Masks

// int32 x = 1;
inline void Masks::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
}
inline ::int32_t Masks::x() const {
  // @@protoc_insertion_point(field_get:imageprocessing.Masks.x)
  return _internal_x();
}
inline void Masks::set_x(::int32_t value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:imageprocessing.Masks.x)
}
inline ::int32_t Masks::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void Masks::_internal_set_x(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// int32 y = 2;
inline void Masks::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
}
inline ::int32_t Masks::y() const {
  // @@protoc_insertion_point(field_get:imageprocessing.Masks.y)
  return _internal_y();
}
inline void Masks::set_y(::int32_t value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:imageprocessing.Masks.y)
}
inline ::int32_t Masks::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void Masks::_internal_set_y(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace imageprocessing


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // perception_2fimgs_2eproto_2epb_2eh
