#include "../pb_export.h"
// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: detection/detection.proto
#ifndef GRPC_detection_2fdetection_2eproto__INCLUDED
#define GRPC_detection_2fdetection_2eproto__INCLUDED

#include "detection/detection.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace detection {

// 目标检测服务
class DETECTION_API ObjectDetection final {
 public:
  static constexpr char const* service_full_name() {
    return "detection.ObjectDetection";
  }
  class DETECTION_API StubInterface {
   public:
    virtual ~StubInterface() {}
    // 单张图像检测
    virtual ::grpc::Status DetectObjects(::grpc::ClientContext* context, const ::detection::DetectionRequest& request, ::detection::DetectionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::detection::DetectionResponse>> AsyncDetectObjects(::grpc::ClientContext* context, const ::detection::DetectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::detection::DetectionResponse>>(AsyncDetectObjectsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::detection::DetectionResponse>> PrepareAsyncDetectObjects(::grpc::ClientContext* context, const ::detection::DetectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::detection::DetectionResponse>>(PrepareAsyncDetectObjectsRaw(context, request, cq));
    }
    // 批量检测
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::detection::DetectionRequest, ::detection::DetectionResponse>> BatchDetect(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::detection::DetectionRequest, ::detection::DetectionResponse>>(BatchDetectRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::detection::DetectionRequest, ::detection::DetectionResponse>> AsyncBatchDetect(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::detection::DetectionRequest, ::detection::DetectionResponse>>(AsyncBatchDetectRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::detection::DetectionRequest, ::detection::DetectionResponse>> PrepareAsyncBatchDetect(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::detection::DetectionRequest, ::detection::DetectionResponse>>(PrepareAsyncBatchDetectRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 单张图像检测
      virtual void DetectObjects(::grpc::ClientContext* context, const ::detection::DetectionRequest* request, ::detection::DetectionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DetectObjects(::grpc::ClientContext* context, const ::detection::DetectionRequest* request, ::detection::DetectionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 批量检测
      virtual void BatchDetect(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::detection::DetectionRequest,::detection::DetectionResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::detection::DetectionResponse>* AsyncDetectObjectsRaw(::grpc::ClientContext* context, const ::detection::DetectionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::detection::DetectionResponse>* PrepareAsyncDetectObjectsRaw(::grpc::ClientContext* context, const ::detection::DetectionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::detection::DetectionRequest, ::detection::DetectionResponse>* BatchDetectRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::detection::DetectionRequest, ::detection::DetectionResponse>* AsyncBatchDetectRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::detection::DetectionRequest, ::detection::DetectionResponse>* PrepareAsyncBatchDetectRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class DETECTION_API Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status DetectObjects(::grpc::ClientContext* context, const ::detection::DetectionRequest& request, ::detection::DetectionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::detection::DetectionResponse>> AsyncDetectObjects(::grpc::ClientContext* context, const ::detection::DetectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::detection::DetectionResponse>>(AsyncDetectObjectsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::detection::DetectionResponse>> PrepareAsyncDetectObjects(::grpc::ClientContext* context, const ::detection::DetectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::detection::DetectionResponse>>(PrepareAsyncDetectObjectsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::detection::DetectionRequest, ::detection::DetectionResponse>> BatchDetect(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::detection::DetectionRequest, ::detection::DetectionResponse>>(BatchDetectRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::detection::DetectionRequest, ::detection::DetectionResponse>> AsyncBatchDetect(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::detection::DetectionRequest, ::detection::DetectionResponse>>(AsyncBatchDetectRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::detection::DetectionRequest, ::detection::DetectionResponse>> PrepareAsyncBatchDetect(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::detection::DetectionRequest, ::detection::DetectionResponse>>(PrepareAsyncBatchDetectRaw(context, cq));
    }
    class DETECTION_API async final :
      public StubInterface::async_interface {
     public:
      void DetectObjects(::grpc::ClientContext* context, const ::detection::DetectionRequest* request, ::detection::DetectionResponse* response, std::function<void(::grpc::Status)>) override;
      void DetectObjects(::grpc::ClientContext* context, const ::detection::DetectionRequest* request, ::detection::DetectionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void BatchDetect(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::detection::DetectionRequest,::detection::DetectionResponse>* reactor) override;
     private:
      friend class DETECTION_API Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::detection::DetectionResponse>* AsyncDetectObjectsRaw(::grpc::ClientContext* context, const ::detection::DetectionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::detection::DetectionResponse>* PrepareAsyncDetectObjectsRaw(::grpc::ClientContext* context, const ::detection::DetectionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::detection::DetectionRequest, ::detection::DetectionResponse>* BatchDetectRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::detection::DetectionRequest, ::detection::DetectionResponse>* AsyncBatchDetectRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::detection::DetectionRequest, ::detection::DetectionResponse>* PrepareAsyncBatchDetectRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_DetectObjects_;
    const ::grpc::internal::RpcMethod rpcmethod_BatchDetect_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class DETECTION_API Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 单张图像检测
    virtual ::grpc::Status DetectObjects(::grpc::ServerContext* context, const ::detection::DetectionRequest* request, ::detection::DetectionResponse* response);
    // 批量检测
    virtual ::grpc::Status BatchDetect(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::detection::DetectionResponse, ::detection::DetectionRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_DetectObjects : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DetectObjects() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_DetectObjects() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectObjects(::grpc::ServerContext* /*context*/, const ::detection::DetectionRequest* /*request*/, ::detection::DetectionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDetectObjects(::grpc::ServerContext* context, ::detection::DetectionRequest* request, ::grpc::ServerAsyncResponseWriter< ::detection::DetectionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_BatchDetect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_BatchDetect() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_BatchDetect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchDetect(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::detection::DetectionResponse, ::detection::DetectionRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBatchDetect(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::detection::DetectionResponse, ::detection::DetectionRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_DetectObjects<WithAsyncMethod_BatchDetect<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_DetectObjects : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DetectObjects() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::detection::DetectionRequest, ::detection::DetectionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::detection::DetectionRequest* request, ::detection::DetectionResponse* response) { return this->DetectObjects(context, request, response); }));}
    void SetMessageAllocatorFor_DetectObjects(
        ::grpc::MessageAllocator< ::detection::DetectionRequest, ::detection::DetectionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::detection::DetectionRequest, ::detection::DetectionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DetectObjects() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectObjects(::grpc::ServerContext* /*context*/, const ::detection::DetectionRequest* /*request*/, ::detection::DetectionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DetectObjects(
      ::grpc::CallbackServerContext* /*context*/, const ::detection::DetectionRequest* /*request*/, ::detection::DetectionResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_BatchDetect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_BatchDetect() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::detection::DetectionRequest, ::detection::DetectionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->BatchDetect(context); }));
    }
    ~WithCallbackMethod_BatchDetect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchDetect(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::detection::DetectionResponse, ::detection::DetectionRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::detection::DetectionRequest, ::detection::DetectionResponse>* BatchDetect(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_DetectObjects<WithCallbackMethod_BatchDetect<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_DetectObjects : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DetectObjects() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_DetectObjects() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectObjects(::grpc::ServerContext* /*context*/, const ::detection::DetectionRequest* /*request*/, ::detection::DetectionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_BatchDetect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_BatchDetect() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_BatchDetect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchDetect(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::detection::DetectionResponse, ::detection::DetectionRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_DetectObjects : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DetectObjects() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_DetectObjects() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectObjects(::grpc::ServerContext* /*context*/, const ::detection::DetectionRequest* /*request*/, ::detection::DetectionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDetectObjects(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_BatchDetect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_BatchDetect() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_BatchDetect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchDetect(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::detection::DetectionResponse, ::detection::DetectionRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBatchDetect(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DetectObjects : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DetectObjects() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DetectObjects(context, request, response); }));
    }
    ~WithRawCallbackMethod_DetectObjects() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectObjects(::grpc::ServerContext* /*context*/, const ::detection::DetectionRequest* /*request*/, ::detection::DetectionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DetectObjects(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_BatchDetect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_BatchDetect() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->BatchDetect(context); }));
    }
    ~WithRawCallbackMethod_BatchDetect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchDetect(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::detection::DetectionResponse, ::detection::DetectionRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* BatchDetect(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DetectObjects : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DetectObjects() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::detection::DetectionRequest, ::detection::DetectionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::detection::DetectionRequest, ::detection::DetectionResponse>* streamer) {
                       return this->StreamedDetectObjects(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DetectObjects() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DetectObjects(::grpc::ServerContext* /*context*/, const ::detection::DetectionRequest* /*request*/, ::detection::DetectionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDetectObjects(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::detection::DetectionRequest,::detection::DetectionResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_DetectObjects<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_DetectObjects<Service > StreamedService;
};

}  // namespace detection


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_detection_2fdetection_2eproto__INCLUDED
