#include "../pb_export.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: detection/detection.proto
// Protobuf C++ Version: 5.29.3

#ifndef detection_2fdetection_2eproto_2epb_2eh
#define detection_2fdetection_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_detection_2fdetection_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_detection_2fdetection_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_detection_2fdetection_2eproto;
namespace detection {
class BoundingBox;
struct BoundingBoxDefaultTypeInternal;
extern BoundingBoxDefaultTypeInternal _BoundingBox_default_instance_;
class DetectionRequest;
struct DetectionRequestDefaultTypeInternal;
extern DetectionRequestDefaultTypeInternal _DetectionRequest_default_instance_;
class DetectionResponse;
struct DetectionResponseDefaultTypeInternal;
extern DetectionResponseDefaultTypeInternal _DetectionResponse_default_instance_;
class DetectionResult;
struct DetectionResultDefaultTypeInternal;
extern DetectionResultDefaultTypeInternal _DetectionResult_default_instance_;
}  // namespace detection
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace detection {

// ===================================================================


// -------------------------------------------------------------------

class DETECTION_API DetectionRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:detection.DetectionRequest) */ {
 public:
  inline DetectionRequest() : DetectionRequest(nullptr) {}
  ~DetectionRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DetectionRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DetectionRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DetectionRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline DetectionRequest(const DetectionRequest& from) : DetectionRequest(nullptr, from) {}
  inline DetectionRequest(DetectionRequest&& from) noexcept
      : DetectionRequest(nullptr, std::move(from)) {}
  inline DetectionRequest& operator=(const DetectionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline DetectionRequest& operator=(DetectionRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DetectionRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const DetectionRequest* internal_default_instance() {
    return reinterpret_cast<const DetectionRequest*>(
        &_DetectionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(DetectionRequest& a, DetectionRequest& b) { a.Swap(&b); }
  inline void Swap(DetectionRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DetectionRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DetectionRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DetectionRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DetectionRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DetectionRequest& from) { DetectionRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DetectionRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "detection.DetectionRequest"; }

 protected:
  explicit DetectionRequest(::google::protobuf::Arena* arena);
  DetectionRequest(::google::protobuf::Arena* arena, const DetectionRequest& from);
  DetectionRequest(::google::protobuf::Arena* arena, DetectionRequest&& from) noexcept
      : DetectionRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kClassesFieldNumber = 3,
    kImageDataFieldNumber = 1,
    kFormatFieldNumber = 2,
  };
  // repeated string classes = 3;
  int classes_size() const;
  private:
  int _internal_classes_size() const;

  public:
  void clear_classes() ;
  const std::string& classes(int index) const;
  std::string* mutable_classes(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_classes(int index, Arg_&& value, Args_... args);
  std::string* add_classes();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_classes(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& classes() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_classes();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_classes() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_classes();

  public:
  // bytes image_data = 1;
  void clear_image_data() ;
  const std::string& image_data() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_image_data(Arg_&& arg, Args_... args);
  std::string* mutable_image_data();
  PROTOBUF_NODISCARD std::string* release_image_data();
  void set_allocated_image_data(std::string* value);

  private:
  const std::string& _internal_image_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_image_data(
      const std::string& value);
  std::string* _internal_mutable_image_data();

  public:
  // string format = 2;
  void clear_format() ;
  const std::string& format() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_format(Arg_&& arg, Args_... args);
  std::string* mutable_format();
  PROTOBUF_NODISCARD std::string* release_format();
  void set_allocated_format(std::string* value);

  private:
  const std::string& _internal_format() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_format(
      const std::string& value);
  std::string* _internal_mutable_format();

  public:
  // @@protoc_insertion_point(class_scope:detection.DetectionRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      48, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DetectionRequest& from_msg);
    ::google::protobuf::RepeatedPtrField<std::string> classes_;
    ::google::protobuf::internal::ArenaStringPtr image_data_;
    ::google::protobuf::internal::ArenaStringPtr format_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_detection_2fdetection_2eproto;
};
// -------------------------------------------------------------------

class DETECTION_API BoundingBox final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:detection.BoundingBox) */ {
 public:
  inline BoundingBox() : BoundingBox(nullptr) {}
  ~BoundingBox() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BoundingBox* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BoundingBox));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BoundingBox(
      ::google::protobuf::internal::ConstantInitialized);

  inline BoundingBox(const BoundingBox& from) : BoundingBox(nullptr, from) {}
  inline BoundingBox(BoundingBox&& from) noexcept
      : BoundingBox(nullptr, std::move(from)) {}
  inline BoundingBox& operator=(const BoundingBox& from) {
    CopyFrom(from);
    return *this;
  }
  inline BoundingBox& operator=(BoundingBox&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BoundingBox& default_instance() {
    return *internal_default_instance();
  }
  static inline const BoundingBox* internal_default_instance() {
    return reinterpret_cast<const BoundingBox*>(
        &_BoundingBox_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(BoundingBox& a, BoundingBox& b) { a.Swap(&b); }
  inline void Swap(BoundingBox* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BoundingBox* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BoundingBox* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BoundingBox>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BoundingBox& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BoundingBox& from) { BoundingBox::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BoundingBox* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "detection.BoundingBox"; }

 protected:
  explicit BoundingBox(::google::protobuf::Arena* arena);
  BoundingBox(::google::protobuf::Arena* arena, const BoundingBox& from);
  BoundingBox(::google::protobuf::Arena* arena, BoundingBox&& from) noexcept
      : BoundingBox(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kWidthFieldNumber = 3,
    kHeightFieldNumber = 4,
  };
  // float x = 1;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 2;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // float width = 3;
  void clear_width() ;
  float width() const;
  void set_width(float value);

  private:
  float _internal_width() const;
  void _internal_set_width(float value);

  public:
  // float height = 4;
  void clear_height() ;
  float height() const;
  void set_height(float value);

  private:
  float _internal_height() const;
  void _internal_set_height(float value);

  public:
  // @@protoc_insertion_point(class_scope:detection.BoundingBox)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BoundingBox& from_msg);
    float x_;
    float y_;
    float width_;
    float height_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_detection_2fdetection_2eproto;
};
// -------------------------------------------------------------------

class DETECTION_API DetectionResult final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:detection.DetectionResult) */ {
 public:
  inline DetectionResult() : DetectionResult(nullptr) {}
  ~DetectionResult() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DetectionResult* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DetectionResult));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DetectionResult(
      ::google::protobuf::internal::ConstantInitialized);

  inline DetectionResult(const DetectionResult& from) : DetectionResult(nullptr, from) {}
  inline DetectionResult(DetectionResult&& from) noexcept
      : DetectionResult(nullptr, std::move(from)) {}
  inline DetectionResult& operator=(const DetectionResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline DetectionResult& operator=(DetectionResult&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DetectionResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const DetectionResult* internal_default_instance() {
    return reinterpret_cast<const DetectionResult*>(
        &_DetectionResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(DetectionResult& a, DetectionResult& b) { a.Swap(&b); }
  inline void Swap(DetectionResult* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DetectionResult* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DetectionResult* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DetectionResult>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DetectionResult& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DetectionResult& from) { DetectionResult::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DetectionResult* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "detection.DetectionResult"; }

 protected:
  explicit DetectionResult(::google::protobuf::Arena* arena);
  DetectionResult(::google::protobuf::Arena* arena, const DetectionResult& from);
  DetectionResult(::google::protobuf::Arena* arena, DetectionResult&& from) noexcept
      : DetectionResult(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kObjectIdFieldNumber = 1,
    kClassNameFieldNumber = 2,
    kBboxFieldNumber = 4,
    kConfidenceFieldNumber = 3,
  };
  // string object_id = 1;
  void clear_object_id() ;
  const std::string& object_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_object_id(Arg_&& arg, Args_... args);
  std::string* mutable_object_id();
  PROTOBUF_NODISCARD std::string* release_object_id();
  void set_allocated_object_id(std::string* value);

  private:
  const std::string& _internal_object_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_object_id(
      const std::string& value);
  std::string* _internal_mutable_object_id();

  public:
  // string class_name = 2;
  void clear_class_name() ;
  const std::string& class_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_class_name(Arg_&& arg, Args_... args);
  std::string* mutable_class_name();
  PROTOBUF_NODISCARD std::string* release_class_name();
  void set_allocated_class_name(std::string* value);

  private:
  const std::string& _internal_class_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_class_name(
      const std::string& value);
  std::string* _internal_mutable_class_name();

  public:
  // .detection.BoundingBox bbox = 4;
  bool has_bbox() const;
  void clear_bbox() ;
  const ::detection::BoundingBox& bbox() const;
  PROTOBUF_NODISCARD ::detection::BoundingBox* release_bbox();
  ::detection::BoundingBox* mutable_bbox();
  void set_allocated_bbox(::detection::BoundingBox* value);
  void unsafe_arena_set_allocated_bbox(::detection::BoundingBox* value);
  ::detection::BoundingBox* unsafe_arena_release_bbox();

  private:
  const ::detection::BoundingBox& _internal_bbox() const;
  ::detection::BoundingBox* _internal_mutable_bbox();

  public:
  // float confidence = 3;
  void clear_confidence() ;
  float confidence() const;
  void set_confidence(float value);

  private:
  float _internal_confidence() const;
  void _internal_set_confidence(float value);

  public:
  // @@protoc_insertion_point(class_scope:detection.DetectionResult)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 1,
      53, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DetectionResult& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr object_id_;
    ::google::protobuf::internal::ArenaStringPtr class_name_;
    ::detection::BoundingBox* bbox_;
    float confidence_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_detection_2fdetection_2eproto;
};
// -------------------------------------------------------------------

class DETECTION_API DetectionResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:detection.DetectionResponse) */ {
 public:
  inline DetectionResponse() : DetectionResponse(nullptr) {}
  ~DetectionResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DetectionResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DetectionResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DetectionResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline DetectionResponse(const DetectionResponse& from) : DetectionResponse(nullptr, from) {}
  inline DetectionResponse(DetectionResponse&& from) noexcept
      : DetectionResponse(nullptr, std::move(from)) {}
  inline DetectionResponse& operator=(const DetectionResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline DetectionResponse& operator=(DetectionResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DetectionResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const DetectionResponse* internal_default_instance() {
    return reinterpret_cast<const DetectionResponse*>(
        &_DetectionResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(DetectionResponse& a, DetectionResponse& b) { a.Swap(&b); }
  inline void Swap(DetectionResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DetectionResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DetectionResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DetectionResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DetectionResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DetectionResponse& from) { DetectionResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DetectionResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "detection.DetectionResponse"; }

 protected:
  explicit DetectionResponse(::google::protobuf::Arena* arena);
  DetectionResponse(::google::protobuf::Arena* arena, const DetectionResponse& from);
  DetectionResponse(::google::protobuf::Arena* arena, DetectionResponse&& from) noexcept
      : DetectionResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResultsFieldNumber = 1,
    kTimestampFieldNumber = 2,
    kSuccessFieldNumber = 3,
  };
  // repeated .detection.DetectionResult results = 1;
  int results_size() const;
  private:
  int _internal_results_size() const;

  public:
  void clear_results() ;
  ::detection::DetectionResult* mutable_results(int index);
  ::google::protobuf::RepeatedPtrField<::detection::DetectionResult>* mutable_results();

  private:
  const ::google::protobuf::RepeatedPtrField<::detection::DetectionResult>& _internal_results() const;
  ::google::protobuf::RepeatedPtrField<::detection::DetectionResult>* _internal_mutable_results();
  public:
  const ::detection::DetectionResult& results(int index) const;
  ::detection::DetectionResult* add_results();
  const ::google::protobuf::RepeatedPtrField<::detection::DetectionResult>& results() const;
  // int64 timestamp = 2;
  void clear_timestamp() ;
  ::int64_t timestamp() const;
  void set_timestamp(::int64_t value);

  private:
  ::int64_t _internal_timestamp() const;
  void _internal_set_timestamp(::int64_t value);

  public:
  // bool success = 3;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // @@protoc_insertion_point(class_scope:detection.DetectionResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DetectionResponse& from_msg);
    ::google::protobuf::RepeatedPtrField< ::detection::DetectionResult > results_;
    ::int64_t timestamp_;
    bool success_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_detection_2fdetection_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DetectionResult

// string object_id = 1;
inline void DetectionResult::clear_object_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.object_id_.ClearToEmpty();
}
inline const std::string& DetectionResult::object_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:detection.DetectionResult.object_id)
  return _internal_object_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DetectionResult::set_object_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.object_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:detection.DetectionResult.object_id)
}
inline std::string* DetectionResult::mutable_object_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_object_id();
  // @@protoc_insertion_point(field_mutable:detection.DetectionResult.object_id)
  return _s;
}
inline const std::string& DetectionResult::_internal_object_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.object_id_.Get();
}
inline void DetectionResult::_internal_set_object_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.object_id_.Set(value, GetArena());
}
inline std::string* DetectionResult::_internal_mutable_object_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.object_id_.Mutable( GetArena());
}
inline std::string* DetectionResult::release_object_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:detection.DetectionResult.object_id)
  return _impl_.object_id_.Release();
}
inline void DetectionResult::set_allocated_object_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.object_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.object_id_.IsDefault()) {
    _impl_.object_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:detection.DetectionResult.object_id)
}

// string class_name = 2;
inline void DetectionResult::clear_class_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.class_name_.ClearToEmpty();
}
inline const std::string& DetectionResult::class_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:detection.DetectionResult.class_name)
  return _internal_class_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DetectionResult::set_class_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.class_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:detection.DetectionResult.class_name)
}
inline std::string* DetectionResult::mutable_class_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_class_name();
  // @@protoc_insertion_point(field_mutable:detection.DetectionResult.class_name)
  return _s;
}
inline const std::string& DetectionResult::_internal_class_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.class_name_.Get();
}
inline void DetectionResult::_internal_set_class_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.class_name_.Set(value, GetArena());
}
inline std::string* DetectionResult::_internal_mutable_class_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.class_name_.Mutable( GetArena());
}
inline std::string* DetectionResult::release_class_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:detection.DetectionResult.class_name)
  return _impl_.class_name_.Release();
}
inline void DetectionResult::set_allocated_class_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.class_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.class_name_.IsDefault()) {
    _impl_.class_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:detection.DetectionResult.class_name)
}

// float confidence = 3;
inline void DetectionResult::clear_confidence() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.confidence_ = 0;
}
inline float DetectionResult::confidence() const {
  // @@protoc_insertion_point(field_get:detection.DetectionResult.confidence)
  return _internal_confidence();
}
inline void DetectionResult::set_confidence(float value) {
  _internal_set_confidence(value);
  // @@protoc_insertion_point(field_set:detection.DetectionResult.confidence)
}
inline float DetectionResult::_internal_confidence() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.confidence_;
}
inline void DetectionResult::_internal_set_confidence(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.confidence_ = value;
}

// .detection.BoundingBox bbox = 4;
inline bool DetectionResult::has_bbox() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.bbox_ != nullptr);
  return value;
}
inline void DetectionResult::clear_bbox() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.bbox_ != nullptr) _impl_.bbox_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::detection::BoundingBox& DetectionResult::_internal_bbox() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::detection::BoundingBox* p = _impl_.bbox_;
  return p != nullptr ? *p : reinterpret_cast<const ::detection::BoundingBox&>(::detection::_BoundingBox_default_instance_);
}
inline const ::detection::BoundingBox& DetectionResult::bbox() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:detection.DetectionResult.bbox)
  return _internal_bbox();
}
inline void DetectionResult::unsafe_arena_set_allocated_bbox(::detection::BoundingBox* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.bbox_);
  }
  _impl_.bbox_ = reinterpret_cast<::detection::BoundingBox*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:detection.DetectionResult.bbox)
}
inline ::detection::BoundingBox* DetectionResult::release_bbox() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::detection::BoundingBox* released = _impl_.bbox_;
  _impl_.bbox_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::detection::BoundingBox* DetectionResult::unsafe_arena_release_bbox() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:detection.DetectionResult.bbox)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::detection::BoundingBox* temp = _impl_.bbox_;
  _impl_.bbox_ = nullptr;
  return temp;
}
inline ::detection::BoundingBox* DetectionResult::_internal_mutable_bbox() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.bbox_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::detection::BoundingBox>(GetArena());
    _impl_.bbox_ = reinterpret_cast<::detection::BoundingBox*>(p);
  }
  return _impl_.bbox_;
}
inline ::detection::BoundingBox* DetectionResult::mutable_bbox() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::detection::BoundingBox* _msg = _internal_mutable_bbox();
  // @@protoc_insertion_point(field_mutable:detection.DetectionResult.bbox)
  return _msg;
}
inline void DetectionResult::set_allocated_bbox(::detection::BoundingBox* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.bbox_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.bbox_ = reinterpret_cast<::detection::BoundingBox*>(value);
  // @@protoc_insertion_point(field_set_allocated:detection.DetectionResult.bbox)
}

// -------------------------------------------------------------------

// BoundingBox

// float x = 1;
inline void BoundingBox::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
}
inline float BoundingBox::x() const {
  // @@protoc_insertion_point(field_get:detection.BoundingBox.x)
  return _internal_x();
}
inline void BoundingBox::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:detection.BoundingBox.x)
}
inline float BoundingBox::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void BoundingBox::_internal_set_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// float y = 2;
inline void BoundingBox::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
}
inline float BoundingBox::y() const {
  // @@protoc_insertion_point(field_get:detection.BoundingBox.y)
  return _internal_y();
}
inline void BoundingBox::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:detection.BoundingBox.y)
}
inline float BoundingBox::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void BoundingBox::_internal_set_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// float width = 3;
inline void BoundingBox::clear_width() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = 0;
}
inline float BoundingBox::width() const {
  // @@protoc_insertion_point(field_get:detection.BoundingBox.width)
  return _internal_width();
}
inline void BoundingBox::set_width(float value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:detection.BoundingBox.width)
}
inline float BoundingBox::_internal_width() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.width_;
}
inline void BoundingBox::_internal_set_width(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = value;
}

// float height = 4;
inline void BoundingBox::clear_height() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = 0;
}
inline float BoundingBox::height() const {
  // @@protoc_insertion_point(field_get:detection.BoundingBox.height)
  return _internal_height();
}
inline void BoundingBox::set_height(float value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:detection.BoundingBox.height)
}
inline float BoundingBox::_internal_height() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.height_;
}
inline void BoundingBox::_internal_set_height(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = value;
}

// -------------------------------------------------------------------

// DetectionRequest

// bytes image_data = 1;
inline void DetectionRequest::clear_image_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_data_.ClearToEmpty();
}
inline const std::string& DetectionRequest::image_data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:detection.DetectionRequest.image_data)
  return _internal_image_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DetectionRequest::set_image_data(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:detection.DetectionRequest.image_data)
}
inline std::string* DetectionRequest::mutable_image_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_image_data();
  // @@protoc_insertion_point(field_mutable:detection.DetectionRequest.image_data)
  return _s;
}
inline const std::string& DetectionRequest::_internal_image_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.image_data_.Get();
}
inline void DetectionRequest::_internal_set_image_data(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_data_.Set(value, GetArena());
}
inline std::string* DetectionRequest::_internal_mutable_image_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.image_data_.Mutable( GetArena());
}
inline std::string* DetectionRequest::release_image_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:detection.DetectionRequest.image_data)
  return _impl_.image_data_.Release();
}
inline void DetectionRequest::set_allocated_image_data(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.image_data_.IsDefault()) {
    _impl_.image_data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:detection.DetectionRequest.image_data)
}

// string format = 2;
inline void DetectionRequest::clear_format() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.format_.ClearToEmpty();
}
inline const std::string& DetectionRequest::format() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:detection.DetectionRequest.format)
  return _internal_format();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DetectionRequest::set_format(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.format_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:detection.DetectionRequest.format)
}
inline std::string* DetectionRequest::mutable_format() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_format();
  // @@protoc_insertion_point(field_mutable:detection.DetectionRequest.format)
  return _s;
}
inline const std::string& DetectionRequest::_internal_format() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.format_.Get();
}
inline void DetectionRequest::_internal_set_format(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.format_.Set(value, GetArena());
}
inline std::string* DetectionRequest::_internal_mutable_format() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.format_.Mutable( GetArena());
}
inline std::string* DetectionRequest::release_format() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:detection.DetectionRequest.format)
  return _impl_.format_.Release();
}
inline void DetectionRequest::set_allocated_format(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.format_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.format_.IsDefault()) {
    _impl_.format_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:detection.DetectionRequest.format)
}

// repeated string classes = 3;
inline int DetectionRequest::_internal_classes_size() const {
  return _internal_classes().size();
}
inline int DetectionRequest::classes_size() const {
  return _internal_classes_size();
}
inline void DetectionRequest::clear_classes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.classes_.Clear();
}
inline std::string* DetectionRequest::add_classes() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_classes()->Add();
  // @@protoc_insertion_point(field_add_mutable:detection.DetectionRequest.classes)
  return _s;
}
inline const std::string& DetectionRequest::classes(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:detection.DetectionRequest.classes)
  return _internal_classes().Get(index);
}
inline std::string* DetectionRequest::mutable_classes(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:detection.DetectionRequest.classes)
  return _internal_mutable_classes()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void DetectionRequest::set_classes(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_classes()->Mutable(index),
      std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:detection.DetectionRequest.classes)
}
template <typename Arg_, typename... Args_>
inline void DetectionRequest::add_classes(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_classes(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:detection.DetectionRequest.classes)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
DetectionRequest::classes() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:detection.DetectionRequest.classes)
  return _internal_classes();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
DetectionRequest::mutable_classes() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:detection.DetectionRequest.classes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_classes();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
DetectionRequest::_internal_classes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.classes_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
DetectionRequest::_internal_mutable_classes() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.classes_;
}

// -------------------------------------------------------------------

// DetectionResponse

// repeated .detection.DetectionResult results = 1;
inline int DetectionResponse::_internal_results_size() const {
  return _internal_results().size();
}
inline int DetectionResponse::results_size() const {
  return _internal_results_size();
}
inline void DetectionResponse::clear_results() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.results_.Clear();
}
inline ::detection::DetectionResult* DetectionResponse::mutable_results(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:detection.DetectionResponse.results)
  return _internal_mutable_results()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::detection::DetectionResult>* DetectionResponse::mutable_results()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:detection.DetectionResponse.results)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_results();
}
inline const ::detection::DetectionResult& DetectionResponse::results(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:detection.DetectionResponse.results)
  return _internal_results().Get(index);
}
inline ::detection::DetectionResult* DetectionResponse::add_results() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::detection::DetectionResult* _add = _internal_mutable_results()->Add();
  // @@protoc_insertion_point(field_add:detection.DetectionResponse.results)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::detection::DetectionResult>& DetectionResponse::results() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:detection.DetectionResponse.results)
  return _internal_results();
}
inline const ::google::protobuf::RepeatedPtrField<::detection::DetectionResult>&
DetectionResponse::_internal_results() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.results_;
}
inline ::google::protobuf::RepeatedPtrField<::detection::DetectionResult>*
DetectionResponse::_internal_mutable_results() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.results_;
}

// int64 timestamp = 2;
inline void DetectionResponse::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = ::int64_t{0};
}
inline ::int64_t DetectionResponse::timestamp() const {
  // @@protoc_insertion_point(field_get:detection.DetectionResponse.timestamp)
  return _internal_timestamp();
}
inline void DetectionResponse::set_timestamp(::int64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:detection.DetectionResponse.timestamp)
}
inline ::int64_t DetectionResponse::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_;
}
inline void DetectionResponse::_internal_set_timestamp(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = value;
}

// bool success = 3;
inline void DetectionResponse::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
}
inline bool DetectionResponse::success() const {
  // @@protoc_insertion_point(field_get:detection.DetectionResponse.success)
  return _internal_success();
}
inline void DetectionResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:detection.DetectionResponse.success)
}
inline bool DetectionResponse::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void DetectionResponse::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace detection


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // detection_2fdetection_2eproto_2epb_2eh
