// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: detection/detection.proto
// Protobuf C++ Version: 5.29.3

#include "detection/detection.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace detection {

inline constexpr DetectionRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : classes_{},
        image_data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        format_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DetectionRequest::DetectionRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DetectionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DetectionRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DetectionRequestDefaultTypeInternal() {}
  union {
    DetectionRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DetectionRequestDefaultTypeInternal _DetectionRequest_default_instance_;

inline constexpr BoundingBox::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : x_{0},
        y_{0},
        width_{0},
        height_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BoundingBox::BoundingBox(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BoundingBoxDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BoundingBoxDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BoundingBoxDefaultTypeInternal() {}
  union {
    BoundingBox _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BoundingBoxDefaultTypeInternal _BoundingBox_default_instance_;

inline constexpr DetectionResult::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        object_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        class_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        bbox_{nullptr},
        confidence_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DetectionResult::DetectionResult(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DetectionResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DetectionResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DetectionResultDefaultTypeInternal() {}
  union {
    DetectionResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DetectionResultDefaultTypeInternal _DetectionResult_default_instance_;

inline constexpr DetectionResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : results_{},
        timestamp_{::int64_t{0}},
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DetectionResponse::DetectionResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DetectionResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DetectionResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DetectionResponseDefaultTypeInternal() {}
  union {
    DetectionResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DetectionResponseDefaultTypeInternal _DetectionResponse_default_instance_;
}  // namespace detection
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_detection_2fdetection_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_detection_2fdetection_2eproto = nullptr;
const ::uint32_t
    TableStruct_detection_2fdetection_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::detection::DetectionResult, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::detection::DetectionResult, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::detection::DetectionResult, _impl_.object_id_),
        PROTOBUF_FIELD_OFFSET(::detection::DetectionResult, _impl_.class_name_),
        PROTOBUF_FIELD_OFFSET(::detection::DetectionResult, _impl_.confidence_),
        PROTOBUF_FIELD_OFFSET(::detection::DetectionResult, _impl_.bbox_),
        ~0u,
        ~0u,
        ~0u,
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::detection::BoundingBox, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::detection::BoundingBox, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::detection::BoundingBox, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::detection::BoundingBox, _impl_.width_),
        PROTOBUF_FIELD_OFFSET(::detection::BoundingBox, _impl_.height_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::detection::DetectionRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::detection::DetectionRequest, _impl_.image_data_),
        PROTOBUF_FIELD_OFFSET(::detection::DetectionRequest, _impl_.format_),
        PROTOBUF_FIELD_OFFSET(::detection::DetectionRequest, _impl_.classes_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::detection::DetectionResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::detection::DetectionResponse, _impl_.results_),
        PROTOBUF_FIELD_OFFSET(::detection::DetectionResponse, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::detection::DetectionResponse, _impl_.success_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 12, -1, sizeof(::detection::DetectionResult)},
        {16, -1, -1, sizeof(::detection::BoundingBox)},
        {28, -1, -1, sizeof(::detection::DetectionRequest)},
        {39, -1, -1, sizeof(::detection::DetectionResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::detection::_DetectionResult_default_instance_._instance,
    &::detection::_BoundingBox_default_instance_._instance,
    &::detection::_DetectionRequest_default_instance_._instance,
    &::detection::_DetectionResponse_default_instance_._instance,
};
const char descriptor_table_protodef_detection_2fdetection_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\031detection/detection.proto\022\tdetection\"r"
    "\n\017DetectionResult\022\021\n\tobject_id\030\001 \001(\t\022\022\n\n"
    "class_name\030\002 \001(\t\022\022\n\nconfidence\030\003 \001(\002\022$\n\004"
    "bbox\030\004 \001(\0132\026.detection.BoundingBox\"B\n\013Bo"
    "undingBox\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\r\n\005width"
    "\030\003 \001(\002\022\016\n\006height\030\004 \001(\002\"G\n\020DetectionReque"
    "st\022\022\n\nimage_data\030\001 \001(\014\022\016\n\006format\030\002 \001(\t\022\017"
    "\n\007classes\030\003 \003(\t\"d\n\021DetectionResponse\022+\n\007"
    "results\030\001 \003(\0132\032.detection.DetectionResul"
    "t\022\021\n\ttimestamp\030\002 \001(\003\022\017\n\007success\030\003 \001(\0102\253\001"
    "\n\017ObjectDetection\022J\n\rDetectObjects\022\033.det"
    "ection.DetectionRequest\032\034.detection.Dete"
    "ctionResponse\022L\n\013BatchDetect\022\033.detection"
    ".DetectionRequest\032\034.detection.DetectionR"
    "esponse(\0010\001b\006proto3"
};
static ::absl::once_flag descriptor_table_detection_2fdetection_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_detection_2fdetection_2eproto = {
    false,
    false,
    579,
    descriptor_table_protodef_detection_2fdetection_2eproto,
    "detection/detection.proto",
    &descriptor_table_detection_2fdetection_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_detection_2fdetection_2eproto::offsets,
    file_level_enum_descriptors_detection_2fdetection_2eproto,
    file_level_service_descriptors_detection_2fdetection_2eproto,
};
namespace detection {
// ===================================================================

class DetectionResult::_Internal {
 public:
  using HasBits =
      decltype(std::declval<DetectionResult>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(DetectionResult, _impl_._has_bits_);
};

DetectionResult::DetectionResult(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:detection.DetectionResult)
}
inline PROTOBUF_NDEBUG_INLINE DetectionResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::detection::DetectionResult& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        object_id_(arena, from.object_id_),
        class_name_(arena, from.class_name_) {}

DetectionResult::DetectionResult(
    ::google::protobuf::Arena* arena,
    const DetectionResult& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DetectionResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.bbox_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::detection::BoundingBox>(
                              arena, *from._impl_.bbox_)
                        : nullptr;
  _impl_.confidence_ = from._impl_.confidence_;

  // @@protoc_insertion_point(copy_constructor:detection.DetectionResult)
}
inline PROTOBUF_NDEBUG_INLINE DetectionResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        object_id_(arena),
        class_name_(arena) {}

inline void DetectionResult::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, bbox_),
           0,
           offsetof(Impl_, confidence_) -
               offsetof(Impl_, bbox_) +
               sizeof(Impl_::confidence_));
}
DetectionResult::~DetectionResult() {
  // @@protoc_insertion_point(destructor:detection.DetectionResult)
  SharedDtor(*this);
}
inline void DetectionResult::SharedDtor(MessageLite& self) {
  DetectionResult& this_ = static_cast<DetectionResult&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.object_id_.Destroy();
  this_._impl_.class_name_.Destroy();
  delete this_._impl_.bbox_;
  this_._impl_.~Impl_();
}

inline void* DetectionResult::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DetectionResult(arena);
}
constexpr auto DetectionResult::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(DetectionResult),
                                            alignof(DetectionResult));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DetectionResult::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DetectionResult_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &DetectionResult::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<DetectionResult>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DetectionResult::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<DetectionResult>(), &DetectionResult::ByteSizeLong,
            &DetectionResult::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DetectionResult, _impl_._cached_size_),
        false,
    },
    &DetectionResult::kDescriptorMethods,
    &descriptor_table_detection_2fdetection_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DetectionResult::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 53, 2> DetectionResult::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(DetectionResult, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::detection::DetectionResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .detection.BoundingBox bbox = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 0, 0, PROTOBUF_FIELD_OFFSET(DetectionResult, _impl_.bbox_)}},
    // string object_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(DetectionResult, _impl_.object_id_)}},
    // string class_name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(DetectionResult, _impl_.class_name_)}},
    // float confidence = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 63, 0, PROTOBUF_FIELD_OFFSET(DetectionResult, _impl_.confidence_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string object_id = 1;
    {PROTOBUF_FIELD_OFFSET(DetectionResult, _impl_.object_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string class_name = 2;
    {PROTOBUF_FIELD_OFFSET(DetectionResult, _impl_.class_name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // float confidence = 3;
    {PROTOBUF_FIELD_OFFSET(DetectionResult, _impl_.confidence_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // .detection.BoundingBox bbox = 4;
    {PROTOBUF_FIELD_OFFSET(DetectionResult, _impl_.bbox_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::detection::BoundingBox>()},
  }}, {{
    "\31\11\12\0\0\0\0\0"
    "detection.DetectionResult"
    "object_id"
    "class_name"
  }},
};

PROTOBUF_NOINLINE void DetectionResult::Clear() {
// @@protoc_insertion_point(message_clear_start:detection.DetectionResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.object_id_.ClearToEmpty();
  _impl_.class_name_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.bbox_ != nullptr);
    _impl_.bbox_->Clear();
  }
  _impl_.confidence_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DetectionResult::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DetectionResult& this_ = static_cast<const DetectionResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DetectionResult::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DetectionResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:detection.DetectionResult)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string object_id = 1;
          if (!this_._internal_object_id().empty()) {
            const std::string& _s = this_._internal_object_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "detection.DetectionResult.object_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string class_name = 2;
          if (!this_._internal_class_name().empty()) {
            const std::string& _s = this_._internal_class_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "detection.DetectionResult.class_name");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // float confidence = 3;
          if (::absl::bit_cast<::uint32_t>(this_._internal_confidence()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                3, this_._internal_confidence(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .detection.BoundingBox bbox = 4;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                4, *this_._impl_.bbox_, this_._impl_.bbox_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:detection.DetectionResult)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DetectionResult::ByteSizeLong(const MessageLite& base) {
          const DetectionResult& this_ = static_cast<const DetectionResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DetectionResult::ByteSizeLong() const {
          const DetectionResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:detection.DetectionResult)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string object_id = 1;
            if (!this_._internal_object_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_object_id());
            }
            // string class_name = 2;
            if (!this_._internal_class_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_class_name());
            }
          }
           {
            // .detection.BoundingBox bbox = 4;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.bbox_);
            }
          }
           {
            // float confidence = 3;
            if (::absl::bit_cast<::uint32_t>(this_._internal_confidence()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DetectionResult::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DetectionResult*>(&to_msg);
  auto& from = static_cast<const DetectionResult&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:detection.DetectionResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_object_id().empty()) {
    _this->_internal_set_object_id(from._internal_object_id());
  }
  if (!from._internal_class_name().empty()) {
    _this->_internal_set_class_name(from._internal_class_name());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.bbox_ != nullptr);
    if (_this->_impl_.bbox_ == nullptr) {
      _this->_impl_.bbox_ =
          ::google::protobuf::Message::CopyConstruct<::detection::BoundingBox>(arena, *from._impl_.bbox_);
    } else {
      _this->_impl_.bbox_->MergeFrom(*from._impl_.bbox_);
    }
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_confidence()) != 0) {
    _this->_impl_.confidence_ = from._impl_.confidence_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DetectionResult::CopyFrom(const DetectionResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:detection.DetectionResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DetectionResult::InternalSwap(DetectionResult* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.object_id_, &other->_impl_.object_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.class_name_, &other->_impl_.class_name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DetectionResult, _impl_.confidence_)
      + sizeof(DetectionResult::_impl_.confidence_)
      - PROTOBUF_FIELD_OFFSET(DetectionResult, _impl_.bbox_)>(
          reinterpret_cast<char*>(&_impl_.bbox_),
          reinterpret_cast<char*>(&other->_impl_.bbox_));
}

::google::protobuf::Metadata DetectionResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BoundingBox::_Internal {
 public:
};

BoundingBox::BoundingBox(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:detection.BoundingBox)
}
BoundingBox::BoundingBox(
    ::google::protobuf::Arena* arena, const BoundingBox& from)
    : BoundingBox(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE BoundingBox::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void BoundingBox::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, height_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::height_));
}
BoundingBox::~BoundingBox() {
  // @@protoc_insertion_point(destructor:detection.BoundingBox)
  SharedDtor(*this);
}
inline void BoundingBox::SharedDtor(MessageLite& self) {
  BoundingBox& this_ = static_cast<BoundingBox&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* BoundingBox::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) BoundingBox(arena);
}
constexpr auto BoundingBox::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(BoundingBox),
                                            alignof(BoundingBox));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull BoundingBox::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_BoundingBox_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &BoundingBox::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<BoundingBox>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &BoundingBox::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<BoundingBox>(), &BoundingBox::ByteSizeLong,
            &BoundingBox::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(BoundingBox, _impl_._cached_size_),
        false,
    },
    &BoundingBox::kDescriptorMethods,
    &descriptor_table_detection_2fdetection_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* BoundingBox::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> BoundingBox::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::detection::BoundingBox>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float height = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 63, 0, PROTOBUF_FIELD_OFFSET(BoundingBox, _impl_.height_)}},
    // float x = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(BoundingBox, _impl_.x_)}},
    // float y = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(BoundingBox, _impl_.y_)}},
    // float width = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 63, 0, PROTOBUF_FIELD_OFFSET(BoundingBox, _impl_.width_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float x = 1;
    {PROTOBUF_FIELD_OFFSET(BoundingBox, _impl_.x_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float y = 2;
    {PROTOBUF_FIELD_OFFSET(BoundingBox, _impl_.y_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float width = 3;
    {PROTOBUF_FIELD_OFFSET(BoundingBox, _impl_.width_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float height = 4;
    {PROTOBUF_FIELD_OFFSET(BoundingBox, _impl_.height_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void BoundingBox::Clear() {
// @@protoc_insertion_point(message_clear_start:detection.BoundingBox)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.height_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.height_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* BoundingBox::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const BoundingBox& this_ = static_cast<const BoundingBox&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* BoundingBox::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const BoundingBox& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:detection.BoundingBox)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // float x = 1;
          if (::absl::bit_cast<::uint32_t>(this_._internal_x()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                1, this_._internal_x(), target);
          }

          // float y = 2;
          if (::absl::bit_cast<::uint32_t>(this_._internal_y()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                2, this_._internal_y(), target);
          }

          // float width = 3;
          if (::absl::bit_cast<::uint32_t>(this_._internal_width()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                3, this_._internal_width(), target);
          }

          // float height = 4;
          if (::absl::bit_cast<::uint32_t>(this_._internal_height()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                4, this_._internal_height(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:detection.BoundingBox)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t BoundingBox::ByteSizeLong(const MessageLite& base) {
          const BoundingBox& this_ = static_cast<const BoundingBox&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t BoundingBox::ByteSizeLong() const {
          const BoundingBox& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:detection.BoundingBox)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // float x = 1;
            if (::absl::bit_cast<::uint32_t>(this_._internal_x()) != 0) {
              total_size += 5;
            }
            // float y = 2;
            if (::absl::bit_cast<::uint32_t>(this_._internal_y()) != 0) {
              total_size += 5;
            }
            // float width = 3;
            if (::absl::bit_cast<::uint32_t>(this_._internal_width()) != 0) {
              total_size += 5;
            }
            // float height = 4;
            if (::absl::bit_cast<::uint32_t>(this_._internal_height()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void BoundingBox::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BoundingBox*>(&to_msg);
  auto& from = static_cast<const BoundingBox&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:detection.BoundingBox)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint32_t>(from._internal_x()) != 0) {
    _this->_impl_.x_ = from._impl_.x_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_y()) != 0) {
    _this->_impl_.y_ = from._impl_.y_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_width()) != 0) {
    _this->_impl_.width_ = from._impl_.width_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_height()) != 0) {
    _this->_impl_.height_ = from._impl_.height_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BoundingBox::CopyFrom(const BoundingBox& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:detection.BoundingBox)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BoundingBox::InternalSwap(BoundingBox* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BoundingBox, _impl_.height_)
      + sizeof(BoundingBox::_impl_.height_)
      - PROTOBUF_FIELD_OFFSET(BoundingBox, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata BoundingBox::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DetectionRequest::_Internal {
 public:
};

DetectionRequest::DetectionRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:detection.DetectionRequest)
}
inline PROTOBUF_NDEBUG_INLINE DetectionRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::detection::DetectionRequest& from_msg)
      : classes_{visibility, arena, from.classes_},
        image_data_(arena, from.image_data_),
        format_(arena, from.format_),
        _cached_size_{0} {}

DetectionRequest::DetectionRequest(
    ::google::protobuf::Arena* arena,
    const DetectionRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DetectionRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:detection.DetectionRequest)
}
inline PROTOBUF_NDEBUG_INLINE DetectionRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : classes_{visibility, arena},
        image_data_(arena),
        format_(arena),
        _cached_size_{0} {}

inline void DetectionRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
DetectionRequest::~DetectionRequest() {
  // @@protoc_insertion_point(destructor:detection.DetectionRequest)
  SharedDtor(*this);
}
inline void DetectionRequest::SharedDtor(MessageLite& self) {
  DetectionRequest& this_ = static_cast<DetectionRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.image_data_.Destroy();
  this_._impl_.format_.Destroy();
  this_._impl_.~Impl_();
}

inline void* DetectionRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DetectionRequest(arena);
}
constexpr auto DetectionRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(DetectionRequest, _impl_.classes_) +
          decltype(DetectionRequest::_impl_.classes_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(DetectionRequest), alignof(DetectionRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&DetectionRequest::PlacementNew_,
                                 sizeof(DetectionRequest),
                                 alignof(DetectionRequest));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DetectionRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DetectionRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &DetectionRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<DetectionRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DetectionRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<DetectionRequest>(), &DetectionRequest::ByteSizeLong,
            &DetectionRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DetectionRequest, _impl_._cached_size_),
        false,
    },
    &DetectionRequest::kDescriptorMethods,
    &descriptor_table_detection_2fdetection_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DetectionRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 48, 2> DetectionRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::detection::DetectionRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bytes image_data = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(DetectionRequest, _impl_.image_data_)}},
    // string format = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(DetectionRequest, _impl_.format_)}},
    // repeated string classes = 3;
    {::_pbi::TcParser::FastUR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(DetectionRequest, _impl_.classes_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes image_data = 1;
    {PROTOBUF_FIELD_OFFSET(DetectionRequest, _impl_.image_data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // string format = 2;
    {PROTOBUF_FIELD_OFFSET(DetectionRequest, _impl_.format_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated string classes = 3;
    {PROTOBUF_FIELD_OFFSET(DetectionRequest, _impl_.classes_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\32\0\6\7\0\0\0\0"
    "detection.DetectionRequest"
    "format"
    "classes"
  }},
};

PROTOBUF_NOINLINE void DetectionRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:detection.DetectionRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.classes_.Clear();
  _impl_.image_data_.ClearToEmpty();
  _impl_.format_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DetectionRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DetectionRequest& this_ = static_cast<const DetectionRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DetectionRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DetectionRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:detection.DetectionRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bytes image_data = 1;
          if (!this_._internal_image_data().empty()) {
            const std::string& _s = this_._internal_image_data();
            target = stream->WriteBytesMaybeAliased(1, _s, target);
          }

          // string format = 2;
          if (!this_._internal_format().empty()) {
            const std::string& _s = this_._internal_format();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "detection.DetectionRequest.format");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // repeated string classes = 3;
          for (int i = 0, n = this_._internal_classes_size(); i < n; ++i) {
            const auto& s = this_._internal_classes().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "detection.DetectionRequest.classes");
            target = stream->WriteString(3, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:detection.DetectionRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DetectionRequest::ByteSizeLong(const MessageLite& base) {
          const DetectionRequest& this_ = static_cast<const DetectionRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DetectionRequest::ByteSizeLong() const {
          const DetectionRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:detection.DetectionRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string classes = 3;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_classes().size());
              for (int i = 0, n = this_._internal_classes().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_classes().Get(i));
              }
            }
          }
           {
            // bytes image_data = 1;
            if (!this_._internal_image_data().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_image_data());
            }
            // string format = 2;
            if (!this_._internal_format().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_format());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DetectionRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DetectionRequest*>(&to_msg);
  auto& from = static_cast<const DetectionRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:detection.DetectionRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_classes()->MergeFrom(from._internal_classes());
  if (!from._internal_image_data().empty()) {
    _this->_internal_set_image_data(from._internal_image_data());
  }
  if (!from._internal_format().empty()) {
    _this->_internal_set_format(from._internal_format());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DetectionRequest::CopyFrom(const DetectionRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:detection.DetectionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DetectionRequest::InternalSwap(DetectionRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.classes_.InternalSwap(&other->_impl_.classes_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.image_data_, &other->_impl_.image_data_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.format_, &other->_impl_.format_, arena);
}

::google::protobuf::Metadata DetectionRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DetectionResponse::_Internal {
 public:
};

DetectionResponse::DetectionResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:detection.DetectionResponse)
}
inline PROTOBUF_NDEBUG_INLINE DetectionResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::detection::DetectionResponse& from_msg)
      : results_{visibility, arena, from.results_},
        _cached_size_{0} {}

DetectionResponse::DetectionResponse(
    ::google::protobuf::Arena* arena,
    const DetectionResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DetectionResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, timestamp_),
           offsetof(Impl_, success_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::success_));

  // @@protoc_insertion_point(copy_constructor:detection.DetectionResponse)
}
inline PROTOBUF_NDEBUG_INLINE DetectionResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : results_{visibility, arena},
        _cached_size_{0} {}

inline void DetectionResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_),
           0,
           offsetof(Impl_, success_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::success_));
}
DetectionResponse::~DetectionResponse() {
  // @@protoc_insertion_point(destructor:detection.DetectionResponse)
  SharedDtor(*this);
}
inline void DetectionResponse::SharedDtor(MessageLite& self) {
  DetectionResponse& this_ = static_cast<DetectionResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* DetectionResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DetectionResponse(arena);
}
constexpr auto DetectionResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(DetectionResponse, _impl_.results_) +
          decltype(DetectionResponse::_impl_.results_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(DetectionResponse), alignof(DetectionResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&DetectionResponse::PlacementNew_,
                                 sizeof(DetectionResponse),
                                 alignof(DetectionResponse));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DetectionResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DetectionResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &DetectionResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<DetectionResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DetectionResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<DetectionResponse>(), &DetectionResponse::ByteSizeLong,
            &DetectionResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DetectionResponse, _impl_._cached_size_),
        false,
    },
    &DetectionResponse::kDescriptorMethods,
    &descriptor_table_detection_2fdetection_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DetectionResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> DetectionResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::detection::DetectionResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated .detection.DetectionResult results = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(DetectionResponse, _impl_.results_)}},
    // int64 timestamp = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(DetectionResponse, _impl_.timestamp_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(DetectionResponse, _impl_.timestamp_)}},
    // bool success = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(DetectionResponse, _impl_.success_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(DetectionResponse, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .detection.DetectionResult results = 1;
    {PROTOBUF_FIELD_OFFSET(DetectionResponse, _impl_.results_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // int64 timestamp = 2;
    {PROTOBUF_FIELD_OFFSET(DetectionResponse, _impl_.timestamp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // bool success = 3;
    {PROTOBUF_FIELD_OFFSET(DetectionResponse, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }}, {{
    {::_pbi::TcParser::GetTable<::detection::DetectionResult>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void DetectionResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:detection.DetectionResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.results_.Clear();
  ::memset(&_impl_.timestamp_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.success_) -
      reinterpret_cast<char*>(&_impl_.timestamp_)) + sizeof(_impl_.success_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DetectionResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DetectionResponse& this_ = static_cast<const DetectionResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DetectionResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DetectionResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:detection.DetectionResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .detection.DetectionResult results = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_results_size());
               i < n; i++) {
            const auto& repfield = this_._internal_results().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // int64 timestamp = 2;
          if (this_._internal_timestamp() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<2>(
                    stream, this_._internal_timestamp(), target);
          }

          // bool success = 3;
          if (this_._internal_success() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_success(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:detection.DetectionResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DetectionResponse::ByteSizeLong(const MessageLite& base) {
          const DetectionResponse& this_ = static_cast<const DetectionResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DetectionResponse::ByteSizeLong() const {
          const DetectionResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:detection.DetectionResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .detection.DetectionResult results = 1;
            {
              total_size += 1UL * this_._internal_results_size();
              for (const auto& msg : this_._internal_results()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // int64 timestamp = 2;
            if (this_._internal_timestamp() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_timestamp());
            }
            // bool success = 3;
            if (this_._internal_success() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DetectionResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DetectionResponse*>(&to_msg);
  auto& from = static_cast<const DetectionResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:detection.DetectionResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_results()->MergeFrom(
      from._internal_results());
  if (from._internal_timestamp() != 0) {
    _this->_impl_.timestamp_ = from._impl_.timestamp_;
  }
  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DetectionResponse::CopyFrom(const DetectionResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:detection.DetectionResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DetectionResponse::InternalSwap(DetectionResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.results_.InternalSwap(&other->_impl_.results_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DetectionResponse, _impl_.success_)
      + sizeof(DetectionResponse::_impl_.success_)
      - PROTOBUF_FIELD_OFFSET(DetectionResponse, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

::google::protobuf::Metadata DetectionResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace detection
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_detection_2fdetection_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
