// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: detection/detection.proto

#include "detection/detection.pb.h"
#include "detection/detection.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace detection {

static const char* ObjectDetection_method_names[] = {
  "/detection.ObjectDetection/DetectObjects",
  "/detection.ObjectDetection/BatchDetect",
};

std::unique_ptr< ObjectDetection::Stub> ObjectDetection::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ObjectDetection::Stub> stub(new ObjectDetection::Stub(channel, options));
  return stub;
}

ObjectDetection::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_DetectObjects_(ObjectDetection_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BatchDetect_(ObjectDetection_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status ObjectDetection::Stub::DetectObjects(::grpc::ClientContext* context, const ::detection::DetectionRequest& request, ::detection::DetectionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::detection::DetectionRequest, ::detection::DetectionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DetectObjects_, context, request, response);
}

void ObjectDetection::Stub::async::DetectObjects(::grpc::ClientContext* context, const ::detection::DetectionRequest* request, ::detection::DetectionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::detection::DetectionRequest, ::detection::DetectionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DetectObjects_, context, request, response, std::move(f));
}

void ObjectDetection::Stub::async::DetectObjects(::grpc::ClientContext* context, const ::detection::DetectionRequest* request, ::detection::DetectionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DetectObjects_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::detection::DetectionResponse>* ObjectDetection::Stub::PrepareAsyncDetectObjectsRaw(::grpc::ClientContext* context, const ::detection::DetectionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::detection::DetectionResponse, ::detection::DetectionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DetectObjects_, context, request);
}

::grpc::ClientAsyncResponseReader< ::detection::DetectionResponse>* ObjectDetection::Stub::AsyncDetectObjectsRaw(::grpc::ClientContext* context, const ::detection::DetectionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDetectObjectsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::detection::DetectionRequest, ::detection::DetectionResponse>* ObjectDetection::Stub::BatchDetectRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::detection::DetectionRequest, ::detection::DetectionResponse>::Create(channel_.get(), rpcmethod_BatchDetect_, context);
}

void ObjectDetection::Stub::async::BatchDetect(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::detection::DetectionRequest,::detection::DetectionResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::detection::DetectionRequest,::detection::DetectionResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_BatchDetect_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::detection::DetectionRequest, ::detection::DetectionResponse>* ObjectDetection::Stub::AsyncBatchDetectRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::detection::DetectionRequest, ::detection::DetectionResponse>::Create(channel_.get(), cq, rpcmethod_BatchDetect_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::detection::DetectionRequest, ::detection::DetectionResponse>* ObjectDetection::Stub::PrepareAsyncBatchDetectRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::detection::DetectionRequest, ::detection::DetectionResponse>::Create(channel_.get(), cq, rpcmethod_BatchDetect_, context, false, nullptr);
}

ObjectDetection::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ObjectDetection_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ObjectDetection::Service, ::detection::DetectionRequest, ::detection::DetectionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ObjectDetection::Service* service,
             ::grpc::ServerContext* ctx,
             const ::detection::DetectionRequest* req,
             ::detection::DetectionResponse* resp) {
               return service->DetectObjects(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ObjectDetection_method_names[1],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< ObjectDetection::Service, ::detection::DetectionRequest, ::detection::DetectionResponse>(
          [](ObjectDetection::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::detection::DetectionResponse,
             ::detection::DetectionRequest>* stream) {
               return service->BatchDetect(ctx, stream);
             }, this)));
}

ObjectDetection::Service::~Service() {
}

::grpc::Status ObjectDetection::Service::DetectObjects(::grpc::ServerContext* context, const ::detection::DetectionRequest* request, ::detection::DetectionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ObjectDetection::Service::BatchDetect(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::detection::DetectionResponse, ::detection::DetectionRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace detection

