// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: perception/imgs.proto
// Protobuf C++ Version: 5.29.3

#include "perception/imgs.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace imageprocessing {

inline constexpr Tracks::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : timestamp_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        tracks_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Tracks::Tracks(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TracksDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TracksDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TracksDefaultTypeInternal() {}
  union {
    Tracks _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TracksDefaultTypeInternal _Tracks_default_instance_;

inline constexpr Masks::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : x_{0},
        y_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Masks::Masks(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MasksDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MasksDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MasksDefaultTypeInternal() {}
  union {
    Masks _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MasksDefaultTypeInternal _Masks_default_instance_;

inline constexpr Img::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : timestamp_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        img_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        requiresmasks_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Img::Img(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ImgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ImgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ImgDefaultTypeInternal() {}
  union {
    Img _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ImgDefaultTypeInternal _Img_default_instance_;

inline constexpr TrackRow::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : mask_{},
        trackid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        cls_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        x1_{0},
        y1_{0},
        x2_{0},
        y2_{0},
        conf_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TrackRow::TrackRow(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TrackRowDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TrackRowDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TrackRowDefaultTypeInternal() {}
  union {
    TrackRow _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TrackRowDefaultTypeInternal _TrackRow_default_instance_;

inline constexpr MasksTracks::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : tracks_{},
        timestamp_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MasksTracks::MasksTracks(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MasksTracksDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MasksTracksDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MasksTracksDefaultTypeInternal() {}
  union {
    MasksTracks _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MasksTracksDefaultTypeInternal _MasksTracks_default_instance_;
}  // namespace imageprocessing
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_perception_2fimgs_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_perception_2fimgs_2eproto = nullptr;
const ::uint32_t
    TableStruct_perception_2fimgs_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::imageprocessing::Img, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::imageprocessing::Img, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::imageprocessing::Img, _impl_.img_),
        PROTOBUF_FIELD_OFFSET(::imageprocessing::Img, _impl_.requiresmasks_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::imageprocessing::Tracks, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::imageprocessing::Tracks, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::imageprocessing::Tracks, _impl_.tracks_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::imageprocessing::MasksTracks, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::imageprocessing::MasksTracks, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::imageprocessing::MasksTracks, _impl_.tracks_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::imageprocessing::TrackRow, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::imageprocessing::TrackRow, _impl_.x1_),
        PROTOBUF_FIELD_OFFSET(::imageprocessing::TrackRow, _impl_.y1_),
        PROTOBUF_FIELD_OFFSET(::imageprocessing::TrackRow, _impl_.x2_),
        PROTOBUF_FIELD_OFFSET(::imageprocessing::TrackRow, _impl_.y2_),
        PROTOBUF_FIELD_OFFSET(::imageprocessing::TrackRow, _impl_.trackid_),
        PROTOBUF_FIELD_OFFSET(::imageprocessing::TrackRow, _impl_.conf_),
        PROTOBUF_FIELD_OFFSET(::imageprocessing::TrackRow, _impl_.cls_),
        PROTOBUF_FIELD_OFFSET(::imageprocessing::TrackRow, _impl_.mask_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::imageprocessing::Masks, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::imageprocessing::Masks, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::imageprocessing::Masks, _impl_.y_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::imageprocessing::Img)},
        {11, -1, -1, sizeof(::imageprocessing::Tracks)},
        {21, -1, -1, sizeof(::imageprocessing::MasksTracks)},
        {31, -1, -1, sizeof(::imageprocessing::TrackRow)},
        {47, -1, -1, sizeof(::imageprocessing::Masks)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::imageprocessing::_Img_default_instance_._instance,
    &::imageprocessing::_Tracks_default_instance_._instance,
    &::imageprocessing::_MasksTracks_default_instance_._instance,
    &::imageprocessing::_TrackRow_default_instance_._instance,
    &::imageprocessing::_Masks_default_instance_._instance,
};
const char descriptor_table_protodef_perception_2fimgs_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025perception/imgs.proto\022\017imageprocessing"
    "\"<\n\003Img\022\021\n\ttimeStamp\030\001 \001(\014\022\013\n\003img\030\002 \001(\014\022"
    "\025\n\rrequiresMasks\030\003 \001(\010\"+\n\006Tracks\022\021\n\ttime"
    "Stamp\030\001 \001(\014\022\016\n\006tracks\030\002 \001(\014\"K\n\013MasksTrac"
    "ks\022\021\n\ttimeStamp\030\001 \001(\014\022)\n\006tracks\030\002 \003(\0132\031."
    "imageprocessing.TrackRow\"\214\001\n\010TrackRow\022\n\n"
    "\002x1\030\001 \001(\002\022\n\n\002y1\030\002 \001(\002\022\n\n\002x2\030\003 \001(\002\022\n\n\002y2\030"
    "\004 \001(\002\022\017\n\007trackId\030\005 \001(\t\022\014\n\004conf\030\006 \001(\002\022\013\n\003"
    "cls\030\007 \001(\t\022$\n\004mask\030\010 \003(\0132\026.imageprocessin"
    "g.Masks\"\035\n\005Masks\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\0052\365"
    "\002\n\017ImageProcessing\022>\n\013singleTrack\022\024.imag"
    "eprocessing.Img\032\027.imageprocessing.Tracks"
    "\"\000\022B\n\nsingleMask\022\024.imageprocessing.Img\032\034"
    ".imageprocessing.MasksTracks\"\000\022F\n\017contin"
    "uousTrack\022\024.imageprocessing.Img\032\027.imagep"
    "rocessing.Tracks\"\000(\0010\001\022J\n\016continuousMask"
    "\022\024.imageprocessing.Img\032\034.imageprocessing"
    ".MasksTracks\"\000(\0010\001\022J\n\016continuousInfo\022\024.i"
    "mageprocessing.Img\032\034.imageprocessing.Mas"
    "ksTracks\"\000(\0010\001b\006proto3"
};
static ::absl::once_flag descriptor_table_perception_2fimgs_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_perception_2fimgs_2eproto = {
    false,
    false,
    782,
    descriptor_table_protodef_perception_2fimgs_2eproto,
    "perception/imgs.proto",
    &descriptor_table_perception_2fimgs_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_perception_2fimgs_2eproto::offsets,
    file_level_enum_descriptors_perception_2fimgs_2eproto,
    file_level_service_descriptors_perception_2fimgs_2eproto,
};
namespace imageprocessing {
// ===================================================================

class Img::_Internal {
 public:
};

Img::Img(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:imageprocessing.Img)
}
inline PROTOBUF_NDEBUG_INLINE Img::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::imageprocessing::Img& from_msg)
      : timestamp_(arena, from.timestamp_),
        img_(arena, from.img_),
        _cached_size_{0} {}

Img::Img(
    ::google::protobuf::Arena* arena,
    const Img& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Img* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.requiresmasks_ = from._impl_.requiresmasks_;

  // @@protoc_insertion_point(copy_constructor:imageprocessing.Img)
}
inline PROTOBUF_NDEBUG_INLINE Img::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : timestamp_(arena),
        img_(arena),
        _cached_size_{0} {}

inline void Img::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.requiresmasks_ = {};
}
Img::~Img() {
  // @@protoc_insertion_point(destructor:imageprocessing.Img)
  SharedDtor(*this);
}
inline void Img::SharedDtor(MessageLite& self) {
  Img& this_ = static_cast<Img&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.timestamp_.Destroy();
  this_._impl_.img_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Img::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Img(arena);
}
constexpr auto Img::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Img),
                                            alignof(Img));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Img::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Img_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Img::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Img>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Img::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Img>(), &Img::ByteSizeLong,
            &Img::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Img, _impl_._cached_size_),
        false,
    },
    &Img::kDescriptorMethods,
    &descriptor_table_perception_2fimgs_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Img::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> Img::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::imageprocessing::Img>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bytes timeStamp = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Img, _impl_.timestamp_)}},
    // bytes img = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Img, _impl_.img_)}},
    // bool requiresMasks = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Img, _impl_.requiresmasks_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Img, _impl_.requiresmasks_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes timeStamp = 1;
    {PROTOBUF_FIELD_OFFSET(Img, _impl_.timestamp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes img = 2;
    {PROTOBUF_FIELD_OFFSET(Img, _impl_.img_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bool requiresMasks = 3;
    {PROTOBUF_FIELD_OFFSET(Img, _impl_.requiresmasks_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Img::Clear() {
// @@protoc_insertion_point(message_clear_start:imageprocessing.Img)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.timestamp_.ClearToEmpty();
  _impl_.img_.ClearToEmpty();
  _impl_.requiresmasks_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Img::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Img& this_ = static_cast<const Img&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Img::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Img& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:imageprocessing.Img)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bytes timeStamp = 1;
          if (!this_._internal_timestamp().empty()) {
            const std::string& _s = this_._internal_timestamp();
            target = stream->WriteBytesMaybeAliased(1, _s, target);
          }

          // bytes img = 2;
          if (!this_._internal_img().empty()) {
            const std::string& _s = this_._internal_img();
            target = stream->WriteBytesMaybeAliased(2, _s, target);
          }

          // bool requiresMasks = 3;
          if (this_._internal_requiresmasks() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_requiresmasks(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:imageprocessing.Img)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Img::ByteSizeLong(const MessageLite& base) {
          const Img& this_ = static_cast<const Img&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Img::ByteSizeLong() const {
          const Img& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:imageprocessing.Img)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bytes timeStamp = 1;
            if (!this_._internal_timestamp().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_timestamp());
            }
            // bytes img = 2;
            if (!this_._internal_img().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_img());
            }
            // bool requiresMasks = 3;
            if (this_._internal_requiresmasks() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Img::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Img*>(&to_msg);
  auto& from = static_cast<const Img&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:imageprocessing.Img)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_timestamp().empty()) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  if (!from._internal_img().empty()) {
    _this->_internal_set_img(from._internal_img());
  }
  if (from._internal_requiresmasks() != 0) {
    _this->_impl_.requiresmasks_ = from._impl_.requiresmasks_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Img::CopyFrom(const Img& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:imageprocessing.Img)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Img::InternalSwap(Img* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.timestamp_, &other->_impl_.timestamp_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.img_, &other->_impl_.img_, arena);
        swap(_impl_.requiresmasks_, other->_impl_.requiresmasks_);
}

::google::protobuf::Metadata Img::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Tracks::_Internal {
 public:
};

Tracks::Tracks(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:imageprocessing.Tracks)
}
inline PROTOBUF_NDEBUG_INLINE Tracks::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::imageprocessing::Tracks& from_msg)
      : timestamp_(arena, from.timestamp_),
        tracks_(arena, from.tracks_),
        _cached_size_{0} {}

Tracks::Tracks(
    ::google::protobuf::Arena* arena,
    const Tracks& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Tracks* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:imageprocessing.Tracks)
}
inline PROTOBUF_NDEBUG_INLINE Tracks::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : timestamp_(arena),
        tracks_(arena),
        _cached_size_{0} {}

inline void Tracks::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Tracks::~Tracks() {
  // @@protoc_insertion_point(destructor:imageprocessing.Tracks)
  SharedDtor(*this);
}
inline void Tracks::SharedDtor(MessageLite& self) {
  Tracks& this_ = static_cast<Tracks&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.timestamp_.Destroy();
  this_._impl_.tracks_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Tracks::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Tracks(arena);
}
constexpr auto Tracks::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Tracks),
                                            alignof(Tracks));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Tracks::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Tracks_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Tracks::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Tracks>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Tracks::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Tracks>(), &Tracks::ByteSizeLong,
            &Tracks::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Tracks, _impl_._cached_size_),
        false,
    },
    &Tracks::kDescriptorMethods,
    &descriptor_table_perception_2fimgs_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Tracks::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Tracks::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::imageprocessing::Tracks>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes tracks = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Tracks, _impl_.tracks_)}},
    // bytes timeStamp = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Tracks, _impl_.timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes timeStamp = 1;
    {PROTOBUF_FIELD_OFFSET(Tracks, _impl_.timestamp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes tracks = 2;
    {PROTOBUF_FIELD_OFFSET(Tracks, _impl_.tracks_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Tracks::Clear() {
// @@protoc_insertion_point(message_clear_start:imageprocessing.Tracks)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.timestamp_.ClearToEmpty();
  _impl_.tracks_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Tracks::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Tracks& this_ = static_cast<const Tracks&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Tracks::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Tracks& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:imageprocessing.Tracks)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bytes timeStamp = 1;
          if (!this_._internal_timestamp().empty()) {
            const std::string& _s = this_._internal_timestamp();
            target = stream->WriteBytesMaybeAliased(1, _s, target);
          }

          // bytes tracks = 2;
          if (!this_._internal_tracks().empty()) {
            const std::string& _s = this_._internal_tracks();
            target = stream->WriteBytesMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:imageprocessing.Tracks)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Tracks::ByteSizeLong(const MessageLite& base) {
          const Tracks& this_ = static_cast<const Tracks&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Tracks::ByteSizeLong() const {
          const Tracks& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:imageprocessing.Tracks)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bytes timeStamp = 1;
            if (!this_._internal_timestamp().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_timestamp());
            }
            // bytes tracks = 2;
            if (!this_._internal_tracks().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_tracks());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Tracks::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Tracks*>(&to_msg);
  auto& from = static_cast<const Tracks&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:imageprocessing.Tracks)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_timestamp().empty()) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  if (!from._internal_tracks().empty()) {
    _this->_internal_set_tracks(from._internal_tracks());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Tracks::CopyFrom(const Tracks& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:imageprocessing.Tracks)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Tracks::InternalSwap(Tracks* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.timestamp_, &other->_impl_.timestamp_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.tracks_, &other->_impl_.tracks_, arena);
}

::google::protobuf::Metadata Tracks::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MasksTracks::_Internal {
 public:
};

MasksTracks::MasksTracks(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:imageprocessing.MasksTracks)
}
inline PROTOBUF_NDEBUG_INLINE MasksTracks::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::imageprocessing::MasksTracks& from_msg)
      : tracks_{visibility, arena, from.tracks_},
        timestamp_(arena, from.timestamp_),
        _cached_size_{0} {}

MasksTracks::MasksTracks(
    ::google::protobuf::Arena* arena,
    const MasksTracks& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MasksTracks* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:imageprocessing.MasksTracks)
}
inline PROTOBUF_NDEBUG_INLINE MasksTracks::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : tracks_{visibility, arena},
        timestamp_(arena),
        _cached_size_{0} {}

inline void MasksTracks::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
MasksTracks::~MasksTracks() {
  // @@protoc_insertion_point(destructor:imageprocessing.MasksTracks)
  SharedDtor(*this);
}
inline void MasksTracks::SharedDtor(MessageLite& self) {
  MasksTracks& this_ = static_cast<MasksTracks&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.timestamp_.Destroy();
  this_._impl_.~Impl_();
}

inline void* MasksTracks::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) MasksTracks(arena);
}
constexpr auto MasksTracks::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(MasksTracks, _impl_.tracks_) +
          decltype(MasksTracks::_impl_.tracks_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(MasksTracks), alignof(MasksTracks), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&MasksTracks::PlacementNew_,
                                 sizeof(MasksTracks),
                                 alignof(MasksTracks));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull MasksTracks::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_MasksTracks_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &MasksTracks::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<MasksTracks>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &MasksTracks::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<MasksTracks>(), &MasksTracks::ByteSizeLong,
            &MasksTracks::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(MasksTracks, _impl_._cached_size_),
        false,
    },
    &MasksTracks::kDescriptorMethods,
    &descriptor_table_perception_2fimgs_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* MasksTracks::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> MasksTracks::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::imageprocessing::MasksTracks>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .imageprocessing.TrackRow tracks = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(MasksTracks, _impl_.tracks_)}},
    // bytes timeStamp = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(MasksTracks, _impl_.timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes timeStamp = 1;
    {PROTOBUF_FIELD_OFFSET(MasksTracks, _impl_.timestamp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // repeated .imageprocessing.TrackRow tracks = 2;
    {PROTOBUF_FIELD_OFFSET(MasksTracks, _impl_.tracks_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::imageprocessing::TrackRow>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void MasksTracks::Clear() {
// @@protoc_insertion_point(message_clear_start:imageprocessing.MasksTracks)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.tracks_.Clear();
  _impl_.timestamp_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MasksTracks::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MasksTracks& this_ = static_cast<const MasksTracks&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MasksTracks::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MasksTracks& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:imageprocessing.MasksTracks)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bytes timeStamp = 1;
          if (!this_._internal_timestamp().empty()) {
            const std::string& _s = this_._internal_timestamp();
            target = stream->WriteBytesMaybeAliased(1, _s, target);
          }

          // repeated .imageprocessing.TrackRow tracks = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_tracks_size());
               i < n; i++) {
            const auto& repfield = this_._internal_tracks().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:imageprocessing.MasksTracks)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MasksTracks::ByteSizeLong(const MessageLite& base) {
          const MasksTracks& this_ = static_cast<const MasksTracks&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MasksTracks::ByteSizeLong() const {
          const MasksTracks& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:imageprocessing.MasksTracks)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .imageprocessing.TrackRow tracks = 2;
            {
              total_size += 1UL * this_._internal_tracks_size();
              for (const auto& msg : this_._internal_tracks()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // bytes timeStamp = 1;
            if (!this_._internal_timestamp().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_timestamp());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MasksTracks::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MasksTracks*>(&to_msg);
  auto& from = static_cast<const MasksTracks&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:imageprocessing.MasksTracks)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_tracks()->MergeFrom(
      from._internal_tracks());
  if (!from._internal_timestamp().empty()) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MasksTracks::CopyFrom(const MasksTracks& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:imageprocessing.MasksTracks)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MasksTracks::InternalSwap(MasksTracks* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.tracks_.InternalSwap(&other->_impl_.tracks_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.timestamp_, &other->_impl_.timestamp_, arena);
}

::google::protobuf::Metadata MasksTracks::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TrackRow::_Internal {
 public:
};

TrackRow::TrackRow(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:imageprocessing.TrackRow)
}
inline PROTOBUF_NDEBUG_INLINE TrackRow::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::imageprocessing::TrackRow& from_msg)
      : mask_{visibility, arena, from.mask_},
        trackid_(arena, from.trackid_),
        cls_(arena, from.cls_),
        _cached_size_{0} {}

TrackRow::TrackRow(
    ::google::protobuf::Arena* arena,
    const TrackRow& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TrackRow* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x1_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, x1_),
           offsetof(Impl_, conf_) -
               offsetof(Impl_, x1_) +
               sizeof(Impl_::conf_));

  // @@protoc_insertion_point(copy_constructor:imageprocessing.TrackRow)
}
inline PROTOBUF_NDEBUG_INLINE TrackRow::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : mask_{visibility, arena},
        trackid_(arena),
        cls_(arena),
        _cached_size_{0} {}

inline void TrackRow::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x1_),
           0,
           offsetof(Impl_, conf_) -
               offsetof(Impl_, x1_) +
               sizeof(Impl_::conf_));
}
TrackRow::~TrackRow() {
  // @@protoc_insertion_point(destructor:imageprocessing.TrackRow)
  SharedDtor(*this);
}
inline void TrackRow::SharedDtor(MessageLite& self) {
  TrackRow& this_ = static_cast<TrackRow&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.trackid_.Destroy();
  this_._impl_.cls_.Destroy();
  this_._impl_.~Impl_();
}

inline void* TrackRow::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TrackRow(arena);
}
constexpr auto TrackRow::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(TrackRow, _impl_.mask_) +
          decltype(TrackRow::_impl_.mask_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(TrackRow), alignof(TrackRow), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&TrackRow::PlacementNew_,
                                 sizeof(TrackRow),
                                 alignof(TrackRow));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TrackRow::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TrackRow_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TrackRow::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TrackRow>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TrackRow::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TrackRow>(), &TrackRow::ByteSizeLong,
            &TrackRow::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TrackRow, _impl_._cached_size_),
        false,
    },
    &TrackRow::kDescriptorMethods,
    &descriptor_table_perception_2fimgs_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TrackRow::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 1, 51, 2> TrackRow::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::imageprocessing::TrackRow>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .imageprocessing.Masks mask = 8;
    {::_pbi::TcParser::FastMtR1,
     {66, 63, 0, PROTOBUF_FIELD_OFFSET(TrackRow, _impl_.mask_)}},
    // float x1 = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(TrackRow, _impl_.x1_)}},
    // float y1 = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(TrackRow, _impl_.y1_)}},
    // float x2 = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 63, 0, PROTOBUF_FIELD_OFFSET(TrackRow, _impl_.x2_)}},
    // float y2 = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 63, 0, PROTOBUF_FIELD_OFFSET(TrackRow, _impl_.y2_)}},
    // string trackId = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(TrackRow, _impl_.trackid_)}},
    // float conf = 6;
    {::_pbi::TcParser::FastF32S1,
     {53, 63, 0, PROTOBUF_FIELD_OFFSET(TrackRow, _impl_.conf_)}},
    // string cls = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(TrackRow, _impl_.cls_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float x1 = 1;
    {PROTOBUF_FIELD_OFFSET(TrackRow, _impl_.x1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float y1 = 2;
    {PROTOBUF_FIELD_OFFSET(TrackRow, _impl_.y1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float x2 = 3;
    {PROTOBUF_FIELD_OFFSET(TrackRow, _impl_.x2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float y2 = 4;
    {PROTOBUF_FIELD_OFFSET(TrackRow, _impl_.y2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // string trackId = 5;
    {PROTOBUF_FIELD_OFFSET(TrackRow, _impl_.trackid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // float conf = 6;
    {PROTOBUF_FIELD_OFFSET(TrackRow, _impl_.conf_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // string cls = 7;
    {PROTOBUF_FIELD_OFFSET(TrackRow, _impl_.cls_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .imageprocessing.Masks mask = 8;
    {PROTOBUF_FIELD_OFFSET(TrackRow, _impl_.mask_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::imageprocessing::Masks>()},
  }}, {{
    "\30\0\0\0\0\7\0\3\0\0\0\0\0\0\0\0"
    "imageprocessing.TrackRow"
    "trackId"
    "cls"
  }},
};

PROTOBUF_NOINLINE void TrackRow::Clear() {
// @@protoc_insertion_point(message_clear_start:imageprocessing.TrackRow)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.mask_.Clear();
  _impl_.trackid_.ClearToEmpty();
  _impl_.cls_.ClearToEmpty();
  ::memset(&_impl_.x1_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.conf_) -
      reinterpret_cast<char*>(&_impl_.x1_)) + sizeof(_impl_.conf_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TrackRow::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TrackRow& this_ = static_cast<const TrackRow&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TrackRow::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TrackRow& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:imageprocessing.TrackRow)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // float x1 = 1;
          if (::absl::bit_cast<::uint32_t>(this_._internal_x1()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                1, this_._internal_x1(), target);
          }

          // float y1 = 2;
          if (::absl::bit_cast<::uint32_t>(this_._internal_y1()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                2, this_._internal_y1(), target);
          }

          // float x2 = 3;
          if (::absl::bit_cast<::uint32_t>(this_._internal_x2()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                3, this_._internal_x2(), target);
          }

          // float y2 = 4;
          if (::absl::bit_cast<::uint32_t>(this_._internal_y2()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                4, this_._internal_y2(), target);
          }

          // string trackId = 5;
          if (!this_._internal_trackid().empty()) {
            const std::string& _s = this_._internal_trackid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "imageprocessing.TrackRow.trackId");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          // float conf = 6;
          if (::absl::bit_cast<::uint32_t>(this_._internal_conf()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                6, this_._internal_conf(), target);
          }

          // string cls = 7;
          if (!this_._internal_cls().empty()) {
            const std::string& _s = this_._internal_cls();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "imageprocessing.TrackRow.cls");
            target = stream->WriteStringMaybeAliased(7, _s, target);
          }

          // repeated .imageprocessing.Masks mask = 8;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_mask_size());
               i < n; i++) {
            const auto& repfield = this_._internal_mask().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    8, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:imageprocessing.TrackRow)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TrackRow::ByteSizeLong(const MessageLite& base) {
          const TrackRow& this_ = static_cast<const TrackRow&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TrackRow::ByteSizeLong() const {
          const TrackRow& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:imageprocessing.TrackRow)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .imageprocessing.Masks mask = 8;
            {
              total_size += 1UL * this_._internal_mask_size();
              for (const auto& msg : this_._internal_mask()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // string trackId = 5;
            if (!this_._internal_trackid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_trackid());
            }
            // string cls = 7;
            if (!this_._internal_cls().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_cls());
            }
            // float x1 = 1;
            if (::absl::bit_cast<::uint32_t>(this_._internal_x1()) != 0) {
              total_size += 5;
            }
            // float y1 = 2;
            if (::absl::bit_cast<::uint32_t>(this_._internal_y1()) != 0) {
              total_size += 5;
            }
            // float x2 = 3;
            if (::absl::bit_cast<::uint32_t>(this_._internal_x2()) != 0) {
              total_size += 5;
            }
            // float y2 = 4;
            if (::absl::bit_cast<::uint32_t>(this_._internal_y2()) != 0) {
              total_size += 5;
            }
            // float conf = 6;
            if (::absl::bit_cast<::uint32_t>(this_._internal_conf()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TrackRow::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TrackRow*>(&to_msg);
  auto& from = static_cast<const TrackRow&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:imageprocessing.TrackRow)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_mask()->MergeFrom(
      from._internal_mask());
  if (!from._internal_trackid().empty()) {
    _this->_internal_set_trackid(from._internal_trackid());
  }
  if (!from._internal_cls().empty()) {
    _this->_internal_set_cls(from._internal_cls());
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_x1()) != 0) {
    _this->_impl_.x1_ = from._impl_.x1_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_y1()) != 0) {
    _this->_impl_.y1_ = from._impl_.y1_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_x2()) != 0) {
    _this->_impl_.x2_ = from._impl_.x2_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_y2()) != 0) {
    _this->_impl_.y2_ = from._impl_.y2_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_conf()) != 0) {
    _this->_impl_.conf_ = from._impl_.conf_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TrackRow::CopyFrom(const TrackRow& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:imageprocessing.TrackRow)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TrackRow::InternalSwap(TrackRow* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.mask_.InternalSwap(&other->_impl_.mask_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.trackid_, &other->_impl_.trackid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cls_, &other->_impl_.cls_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TrackRow, _impl_.conf_)
      + sizeof(TrackRow::_impl_.conf_)
      - PROTOBUF_FIELD_OFFSET(TrackRow, _impl_.x1_)>(
          reinterpret_cast<char*>(&_impl_.x1_),
          reinterpret_cast<char*>(&other->_impl_.x1_));
}

::google::protobuf::Metadata TrackRow::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Masks::_Internal {
 public:
};

Masks::Masks(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:imageprocessing.Masks)
}
Masks::Masks(
    ::google::protobuf::Arena* arena, const Masks& from)
    : Masks(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Masks::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Masks::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, y_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::y_));
}
Masks::~Masks() {
  // @@protoc_insertion_point(destructor:imageprocessing.Masks)
  SharedDtor(*this);
}
inline void Masks::SharedDtor(MessageLite& self) {
  Masks& this_ = static_cast<Masks&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* Masks::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Masks(arena);
}
constexpr auto Masks::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Masks),
                                            alignof(Masks));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Masks::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Masks_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Masks::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Masks>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Masks::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Masks>(), &Masks::ByteSizeLong,
            &Masks::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Masks, _impl_._cached_size_),
        false,
    },
    &Masks::kDescriptorMethods,
    &descriptor_table_perception_2fimgs_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Masks::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Masks::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::imageprocessing::Masks>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 y = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Masks, _impl_.y_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Masks, _impl_.y_)}},
    // int32 x = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Masks, _impl_.x_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Masks, _impl_.x_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 x = 1;
    {PROTOBUF_FIELD_OFFSET(Masks, _impl_.x_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 y = 2;
    {PROTOBUF_FIELD_OFFSET(Masks, _impl_.y_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Masks::Clear() {
// @@protoc_insertion_point(message_clear_start:imageprocessing.Masks)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.y_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.y_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Masks::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Masks& this_ = static_cast<const Masks&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Masks::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Masks& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:imageprocessing.Masks)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 x = 1;
          if (this_._internal_x() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_x(), target);
          }

          // int32 y = 2;
          if (this_._internal_y() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_y(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:imageprocessing.Masks)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Masks::ByteSizeLong(const MessageLite& base) {
          const Masks& this_ = static_cast<const Masks&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Masks::ByteSizeLong() const {
          const Masks& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:imageprocessing.Masks)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 x = 1;
            if (this_._internal_x() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_x());
            }
            // int32 y = 2;
            if (this_._internal_y() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_y());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Masks::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Masks*>(&to_msg);
  auto& from = static_cast<const Masks&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:imageprocessing.Masks)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_x() != 0) {
    _this->_impl_.x_ = from._impl_.x_;
  }
  if (from._internal_y() != 0) {
    _this->_impl_.y_ = from._impl_.y_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Masks::CopyFrom(const Masks& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:imageprocessing.Masks)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Masks::InternalSwap(Masks* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Masks, _impl_.y_)
      + sizeof(Masks::_impl_.y_)
      - PROTOBUF_FIELD_OFFSET(Masks, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata Masks::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace imageprocessing
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_perception_2fimgs_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
