// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: perception/imgs.proto

#include "perception/imgs.pb.h"
#include "perception/imgs.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace imageprocessing {

static const char* ImageProcessing_method_names[] = {
  "/imageprocessing.ImageProcessing/singleTrack",
  "/imageprocessing.ImageProcessing/singleMask",
  "/imageprocessing.ImageProcessing/continuousTrack",
  "/imageprocessing.ImageProcessing/continuousMask",
  "/imageprocessing.ImageProcessing/continuousInfo",
};

std::unique_ptr< ImageProcessing::Stub> ImageProcessing::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ImageProcessing::Stub> stub(new ImageProcessing::Stub(channel, options));
  return stub;
}

ImageProcessing::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_singleTrack_(ImageProcessing_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_singleMask_(ImageProcessing_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_continuousTrack_(ImageProcessing_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_continuousMask_(ImageProcessing_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_continuousInfo_(ImageProcessing_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status ImageProcessing::Stub::singleTrack(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::imageprocessing::Tracks* response) {
  return ::grpc::internal::BlockingUnaryCall< ::imageprocessing::Img, ::imageprocessing::Tracks, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_singleTrack_, context, request, response);
}

void ImageProcessing::Stub::async::singleTrack(::grpc::ClientContext* context, const ::imageprocessing::Img* request, ::imageprocessing::Tracks* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::imageprocessing::Img, ::imageprocessing::Tracks, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_singleTrack_, context, request, response, std::move(f));
}

void ImageProcessing::Stub::async::singleTrack(::grpc::ClientContext* context, const ::imageprocessing::Img* request, ::imageprocessing::Tracks* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_singleTrack_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::imageprocessing::Tracks>* ImageProcessing::Stub::PrepareAsyncsingleTrackRaw(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::imageprocessing::Tracks, ::imageprocessing::Img, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_singleTrack_, context, request);
}

::grpc::ClientAsyncResponseReader< ::imageprocessing::Tracks>* ImageProcessing::Stub::AsyncsingleTrackRaw(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsingleTrackRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ImageProcessing::Stub::singleMask(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::imageprocessing::MasksTracks* response) {
  return ::grpc::internal::BlockingUnaryCall< ::imageprocessing::Img, ::imageprocessing::MasksTracks, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_singleMask_, context, request, response);
}

void ImageProcessing::Stub::async::singleMask(::grpc::ClientContext* context, const ::imageprocessing::Img* request, ::imageprocessing::MasksTracks* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::imageprocessing::Img, ::imageprocessing::MasksTracks, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_singleMask_, context, request, response, std::move(f));
}

void ImageProcessing::Stub::async::singleMask(::grpc::ClientContext* context, const ::imageprocessing::Img* request, ::imageprocessing::MasksTracks* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_singleMask_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::imageprocessing::MasksTracks>* ImageProcessing::Stub::PrepareAsyncsingleMaskRaw(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::imageprocessing::MasksTracks, ::imageprocessing::Img, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_singleMask_, context, request);
}

::grpc::ClientAsyncResponseReader< ::imageprocessing::MasksTracks>* ImageProcessing::Stub::AsyncsingleMaskRaw(::grpc::ClientContext* context, const ::imageprocessing::Img& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsingleMaskRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::imageprocessing::Img, ::imageprocessing::Tracks>* ImageProcessing::Stub::continuousTrackRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::imageprocessing::Img, ::imageprocessing::Tracks>::Create(channel_.get(), rpcmethod_continuousTrack_, context);
}

void ImageProcessing::Stub::async::continuousTrack(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::imageprocessing::Img,::imageprocessing::Tracks>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::imageprocessing::Img,::imageprocessing::Tracks>::Create(stub_->channel_.get(), stub_->rpcmethod_continuousTrack_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::Tracks>* ImageProcessing::Stub::AsynccontinuousTrackRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::imageprocessing::Img, ::imageprocessing::Tracks>::Create(channel_.get(), cq, rpcmethod_continuousTrack_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::Tracks>* ImageProcessing::Stub::PrepareAsynccontinuousTrackRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::imageprocessing::Img, ::imageprocessing::Tracks>::Create(channel_.get(), cq, rpcmethod_continuousTrack_, context, false, nullptr);
}

::grpc::ClientReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* ImageProcessing::Stub::continuousMaskRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::imageprocessing::Img, ::imageprocessing::MasksTracks>::Create(channel_.get(), rpcmethod_continuousMask_, context);
}

void ImageProcessing::Stub::async::continuousMask(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::imageprocessing::Img,::imageprocessing::MasksTracks>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::imageprocessing::Img,::imageprocessing::MasksTracks>::Create(stub_->channel_.get(), stub_->rpcmethod_continuousMask_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* ImageProcessing::Stub::AsynccontinuousMaskRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::imageprocessing::Img, ::imageprocessing::MasksTracks>::Create(channel_.get(), cq, rpcmethod_continuousMask_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* ImageProcessing::Stub::PrepareAsynccontinuousMaskRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::imageprocessing::Img, ::imageprocessing::MasksTracks>::Create(channel_.get(), cq, rpcmethod_continuousMask_, context, false, nullptr);
}

::grpc::ClientReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* ImageProcessing::Stub::continuousInfoRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::imageprocessing::Img, ::imageprocessing::MasksTracks>::Create(channel_.get(), rpcmethod_continuousInfo_, context);
}

void ImageProcessing::Stub::async::continuousInfo(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::imageprocessing::Img,::imageprocessing::MasksTracks>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::imageprocessing::Img,::imageprocessing::MasksTracks>::Create(stub_->channel_.get(), stub_->rpcmethod_continuousInfo_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* ImageProcessing::Stub::AsynccontinuousInfoRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::imageprocessing::Img, ::imageprocessing::MasksTracks>::Create(channel_.get(), cq, rpcmethod_continuousInfo_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::imageprocessing::Img, ::imageprocessing::MasksTracks>* ImageProcessing::Stub::PrepareAsynccontinuousInfoRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::imageprocessing::Img, ::imageprocessing::MasksTracks>::Create(channel_.get(), cq, rpcmethod_continuousInfo_, context, false, nullptr);
}

ImageProcessing::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ImageProcessing_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ImageProcessing::Service, ::imageprocessing::Img, ::imageprocessing::Tracks, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ImageProcessing::Service* service,
             ::grpc::ServerContext* ctx,
             const ::imageprocessing::Img* req,
             ::imageprocessing::Tracks* resp) {
               return service->singleTrack(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ImageProcessing_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ImageProcessing::Service, ::imageprocessing::Img, ::imageprocessing::MasksTracks, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ImageProcessing::Service* service,
             ::grpc::ServerContext* ctx,
             const ::imageprocessing::Img* req,
             ::imageprocessing::MasksTracks* resp) {
               return service->singleMask(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ImageProcessing_method_names[2],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< ImageProcessing::Service, ::imageprocessing::Img, ::imageprocessing::Tracks>(
          [](ImageProcessing::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::imageprocessing::Tracks,
             ::imageprocessing::Img>* stream) {
               return service->continuousTrack(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ImageProcessing_method_names[3],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< ImageProcessing::Service, ::imageprocessing::Img, ::imageprocessing::MasksTracks>(
          [](ImageProcessing::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::imageprocessing::MasksTracks,
             ::imageprocessing::Img>* stream) {
               return service->continuousMask(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ImageProcessing_method_names[4],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< ImageProcessing::Service, ::imageprocessing::Img, ::imageprocessing::MasksTracks>(
          [](ImageProcessing::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::imageprocessing::MasksTracks,
             ::imageprocessing::Img>* stream) {
               return service->continuousInfo(ctx, stream);
             }, this)));
}

ImageProcessing::Service::~Service() {
}

::grpc::Status ImageProcessing::Service::singleTrack(::grpc::ServerContext* context, const ::imageprocessing::Img* request, ::imageprocessing::Tracks* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ImageProcessing::Service::singleMask(::grpc::ServerContext* context, const ::imageprocessing::Img* request, ::imageprocessing::MasksTracks* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ImageProcessing::Service::continuousTrack(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::imageprocessing::Tracks, ::imageprocessing::Img>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ImageProcessing::Service::continuousMask(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::imageprocessing::MasksTracks, ::imageprocessing::Img>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ImageProcessing::Service::continuousInfo(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::imageprocessing::MasksTracks, ::imageprocessing::Img>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace imageprocessing

